[alias]
kcl-lsp-server-release = "run --manifest-path ./kcl-lsp-server-release/Cargo.toml --"

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg",
  "getrandom_backend=\"wasm_js\"",
  "-C",
  "link-arg=-z",
  "-C",
  "link-arg=stack-size=16777216",
]
