fn cube(pos, scale) {
  return startSketchOn(XY)
    |> startProfile(at = [center[0] - size, center[1] - size])
    |> line(endAbsolute = [center[0] + size, center[1] - size])
    |> line(endAbsolute = [center[0] + size, center[1] + size])
    |> line(endAbsolute = [center[0] - size, center[1] + size])
    |> close()
    |> extrude(length = 10)
}

part001 = cube(pos = [0, 0], scale = 10)
part002 = cube(pos = [7, 3], scale = 5)
  |> translate(z = 1)

subtractedPart = subtract(part001, tools = part002)
