use std::collections::BTreeMap;
use std::path::Path;

use serde::Serialize;

use super::kcl_doc;
use super::kcl_doc::ArgKind;
use super::kcl_doc::DocData;

// Export the stdlib signature metadata needed by command-bar type adapters.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct GeneratedStdLibCommand {
    name: String,
    preferred_name: String,
    qual_name: String,
    module_name: String,
    return_type: Option<String>,
    deprecated: bool,
    deprecated_since: Option<String>,
    experimental: bool,
    doc_hidden: bool,
    args: Vec<GeneratedStdLibArg>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct GeneratedStdLibArg {
    name: String,
    ty: Option<String>,
    required: bool,
    special: bool,
    experimental: bool,
    deprecated_since: Option<String>,
}

#[test]
fn export_bindings_stdlib_commands() {
    let commands = kcl_doc::walk_stdlib()
        .all_docs()
        .filter_map(|doc| {
            let DocData::Fn(func) = doc else {
                return None;
            };
            Some((
                func.preferred_name.clone(),
                GeneratedStdLibCommand {
                    name: func.name.clone(),
                    preferred_name: func.preferred_name.clone(),
                    qual_name: func.qual_name.clone(),
                    module_name: func.module_name.clone(),
                    return_type: func.return_type.clone(),
                    deprecated: func.properties.deprecated,
                    deprecated_since: func.properties.deprecated_since.as_ref().map(ToString::to_string),
                    experimental: func.properties.experimental,
                    doc_hidden: func.properties.doc_hidden,
                    args: func
                        .args
                        .iter()
                        .map(|arg| GeneratedStdLibArg {
                            name: arg.name.clone(),
                            ty: arg.ty.clone(),
                            required: arg.kind.required(),
                            special: matches!(arg.kind, ArgKind::Special),
                            experimental: arg.experimental,
                            deprecated_since: arg.deprecated_since.as_ref().map(ToString::to_string),
                        })
                        .collect(),
                },
            ))
        })
        .collect::<BTreeMap<_, _>>();

    let json = serde_json::to_string_pretty(&commands).unwrap();
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("bindings");
    std::fs::create_dir_all(&out_dir).unwrap();
    std::fs::write(
        out_dir.join("StdLibCommands.ts"),
        format!(
            "// This file was generated by `cargo test -p kcl-lib export_bindings`.\n\
             // Do not edit this file by hand.\n\n\
             export const STD_LIB_COMMANDS = {json} as const\n\n\
             export type StdLibCommandName = keyof typeof STD_LIB_COMMANDS\n\
             export type StdLibCommand = (typeof STD_LIB_COMMANDS)[StdLibCommandName]\n\
             export type StdLibCommandArg = StdLibCommand['args'][number]\n"
        ),
    )
    .unwrap();
}
