# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directories:
      - '/'
      - '/packages/codemirror-lang-kcl/'
      - '/packages/codemirror-lsp-client/'
    schedule:
      interval: 'weekly'
    reviewers:
      - franknoirot
      - irev-dev
  - package-ecosystem: 'github-actions' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    reviewers:
      - adamchalmers
      - jessfraz
  - package-ecosystem: 'cargo' # See documentation for possible values
    directory: '/src/wasm-lib/' # Location of package manifests
    schedule:
      interval: 'weekly'
    reviewers:
      - adamchalmers
      - jessfraz
    groups:
      serde-dependencies:
        patterns:
          - "serde*"
