// Counterdrilled Weldment
// A metal weldment consisting of a counterdrilled plate, a centrally mounted housing tube, and four structural support fins.
// Categories: Manufacturing, Construction

// Set units
@settings(defaultLengthUnit = in)

// Define parameters
boltSpacingX = 5
boltSpacingY = 3
boltDiameter = 1 / 4
counterdrillDiameter = 7 / 16
counterdrillDepth = 3 / 16
tubeInnerDiameter = 1 + 1 / 4
tubeThickness = 0.115
tubeHeight = 2
stockThickness = .5

// Calculate the dimensions of the block using the specified bolt spacing. The size of the block can be defined by adding a multiple of the counterdrill diameter to the bolt spacing
blockLength = boltSpacingX + boltDiameter * 6
blockWidth = boltSpacingY + boltDiameter * 6

// Define hole positions
holePositions = [
  [-boltSpacingY / 2, -boltSpacingX / 2],
  [-boltSpacingY / 2, boltSpacingX / 2],
  [boltSpacingY / 2, -boltSpacingX / 2],
  [boltSpacingY / 2, boltSpacingX / 2]
]

// Draw the base plate and cut the counterbored bolt holes using hole::holes
plateSketch = startSketchOn(XY)
  |> startProfile(at = [-blockLength / 2, -blockWidth / 2])
  |> angledLine(angle = 0, length = blockLength, tag = $rectangleSegmentA001)
  |> angledLine(angle = segAng(rectangleSegmentA001) + 90, length = blockWidth, tag = $rectangleSegmentB001)
  |> angledLine(angle = segAng(rectangleSegmentA001), length = -segLen(rectangleSegmentA001), tag = $rectangleSegmentC001)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)], tag = $rectangleSegmentD001)
  |> close()
  |> subtract2d(tool = circle(center = [0, 0], radius = tubeInnerDiameter / 2))

plateBody = extrude(plateSketch, length = stockThickness)
  |> hole::holes(
       face = END,
       cutsAt = holePositions,
       holeBottom = hole::flat(),
       holeBody = hole::blind(depth = stockThickness, diameter = boltDiameter),
       holeType = hole::counterbore(diameter = counterdrillDiameter, depth = counterdrillDepth),
     )
  |> chamfer(
       length = boltDiameter * 2,
       tags = [
         getNextAdjacentEdge(rectangleSegmentB001),
         getNextAdjacentEdge(rectangleSegmentA001),
         getNextAdjacentEdge(rectangleSegmentC001),
         getNextAdjacentEdge(rectangleSegmentD001)
       ],
     )

// Drill a small pin hole in the side of the tube
pinhole = startSketchOn(YZ)
  |> circle(center = [0, 2.2], radius = 0.125)
  |> extrude(length = -10)

// Model the central tube and subtract the pin hole
centralTube = startSketchOn(offsetPlane(XY, offset = stockThickness))
  |> circle(center = [0, 0], radius = tubeInnerDiameter / 2 + tubeThickness)
  |> subtract2d(tool = circle(center = [0, 0], radius = tubeInnerDiameter / 2))
  |> extrude(length = tubeHeight)
  |> subtract(tools = [pinhole])

// Sketch a fin which spans from the central tube to the bolt hole
diagPlane = {
  origin = [0.0, 0.0, 0.0],
  xAxis = [
    boltSpacingX / 2,
    boltSpacingY / 2,
    0.0
  ],
  yAxis = [0.0, 0.0, 1.0]
}

finSketch = startSketchOn(diagPlane)
  |> startProfile(at = [
       tubeInnerDiameter / 2 + tubeThickness,
       stockThickness
     ])
  |> xLine(endAbsolute = sqrt((boltSpacingX / 2) ^ 2 + (boltSpacingY / 2) ^ 2) - counterdrillDiameter)
  |> yLine(length = 0.15)
  |> line(endAbsolute = [
       profileStartX(%) + 0.15,
       stockThickness + tubeHeight * .8
     ])
  |> xLine(length = -0.15)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
  |> extrude(length = tubeThickness, symmetric = true)

// Use circular patterns to create the other 3 fins
otherFins = patternCircular3d(
       finSketch,
       instances = 2,
       axis = [0, 0, 1],
       center = [0, 0, 0],
       arcDegrees = 360,
       rotateDuplicates = true,
     )
  |> patternCircular3d(
       instances = 2,
       axis = Z,
       arcDegrees = -2 * atan(boltSpacingY / boltSpacingX),
       center = [0, 0, 0],
     )
