import { AreaType, LayoutType, type Layout } from '@src/lib/layout/types'

export const testLayoutConfig: Layout = {
  id: 'test',
  label: 'root',
  type: LayoutType.Splits,
  orientation: 'block',
  sizes: [30, 20, 40],
  children: [
    {
      id: crypto.randomUUID(),
      label: 'split',
      type: LayoutType.Splits,
      sizes: [50, 25, 25],
      orientation: 'inline',
      children: [
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: LayoutType.Simple,
          areaType: AreaType.ModelingScene,
        },
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: LayoutType.Simple,
          areaType: AreaType.Variables,
        },
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: LayoutType.Simple,
          areaType: AreaType.ModelingScene,
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      label: 'middle-split',
      type: LayoutType.Splits,
      sizes: [75, 25],
      orientation: 'inline',
      children: [
        {
          id: crypto.randomUUID(),
          label: 'right-toolbar',
          type: LayoutType.Panes,
          side: 'inline-end',
          splitOrientation: 'block',
          activeIndices: [0, 2, 3],
          sizes: [20, 20, 60],
          children: [
            {
              id: crypto.randomUUID(),
              label: crypto.randomUUID(),
              type: LayoutType.Simple,
              areaType: AreaType.TTC,
              icon: 'sparkles',
            },
            {
              id: crypto.randomUUID(),
              label: crypto.randomUUID(),
              type: LayoutType.Simple,
              areaType: AreaType.Variables,
              icon: 'make-variable',
            },
            {
              id: crypto.randomUUID(),
              label: 'right-toolbar',
              type: LayoutType.Panes,
              side: 'block-start',
              splitOrientation: 'inline',
              activeIndices: [0, 2, 3],
              sizes: [20, 20, 60],
              icon: 'glasses',
              children: [
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: LayoutType.Simple,
                  areaType: AreaType.TTC,
                  icon: 'sparkles',
                },
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: LayoutType.Simple,
                  areaType: AreaType.Variables,
                  icon: 'make-variable',
                },
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: LayoutType.Simple,
                  areaType: AreaType.Code,
                  icon: 'code',
                },
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: LayoutType.Simple,
                  areaType: AreaType.FeatureTree,
                  icon: 'revolve',
                },
              ],
            },
            {
              id: crypto.randomUUID(),
              label: crypto.randomUUID(),
              type: LayoutType.Simple,
              areaType: AreaType.ModelingScene,
              icon: 'revolve',
            },
          ],
        },
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: LayoutType.Simple,
          areaType: AreaType.ModelingScene,
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      label: 'right-toolbar',
      type: LayoutType.Panes,
      side: 'block-start',
      splitOrientation: 'inline',
      activeIndices: [0, 2, 3],
      sizes: [20, 20, 60],
      children: [
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: LayoutType.Simple,
          areaType: AreaType.TTC,
          icon: 'sparkles',
        },
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: LayoutType.Simple,
          areaType: AreaType.Variables,
          icon: 'make-variable',
        },
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: LayoutType.Simple,
          areaType: AreaType.Code,
          icon: 'code',
        },
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: LayoutType.Simple,
          areaType: AreaType.FeatureTree,
          icon: 'revolve',
        },
      ],
    },
  ],
}
