export const LOCAL_WEBGPU_RENDERING_ENABLED = true
export const LOCAL_WEBGPU_GTAO_USE_NORMAL_MRT = true
export const LOCAL_WEBGPU_GTAO_USE_DENOISE = true
export const LOCAL_WEBGPU_GTAO_SAMPLES = 16
export const LOCAL_WEBGPU_EDGE_LINE_WIDTH_PX = 2
export const LOCAL_WEBGPU_SKETCH_LINE_WIDTH_PX = 2
