export const TOOLBAR_COMMAND_IDS = {
  modeling: {
    sketch: 'zds.toolbar.modeling.sketch',
  },
  sketching: {
    exit: 'zds.toolbar.sketchLegacy.exit',
    cancelTool: 'zds.toolbar.sketchLegacy.cancelTool',
    line: 'zds.toolbar.sketchLegacy.line',
    threePointArc: 'zds.toolbar.sketchLegacy.threePointArc',
    tangentialArc: 'zds.toolbar.sketchLegacy.tangentialArc',
    circleCenter: 'zds.toolbar.sketchLegacy.circleCenter',
    circleThreePoints: 'zds.toolbar.sketchLegacy.circleThreePoints',
    cornerRectangle: 'zds.toolbar.sketchLegacy.cornerRectangle',
    centerRectangle: 'zds.toolbar.sketchLegacy.centerRectangle',
  },
  sketchSolve: {
    exit: 'zds.toolbar.sketch.exit',
    cancel: 'zds.toolbar.sketch.cancel',
    line: 'zds.toolbar.sketch.line',
    point: 'zds.toolbar.sketch.point',
    spline: 'zds.toolbar.sketch.spline',
    circleCenter: 'zds.toolbar.sketch.circleCenter',
    centerArc: 'zds.toolbar.sketch.centerArc',
    threePointArc: 'zds.toolbar.sketch.threePointArc',
    tangentialArc: 'zds.toolbar.sketch.tangentialArc',
    trim: 'zds.toolbar.sketch.trim',
    cornerRectangle: 'zds.toolbar.sketch.cornerRectangle',
    centerRectangle: 'zds.toolbar.sketch.centerRectangle',
    angledRectangle: 'zds.toolbar.sketch.angledRectangle',
    coincident: 'zds.toolbar.sketch.coincident',
    midpoint: 'zds.toolbar.sketch.midpoint',
    tangent: 'zds.toolbar.sketch.tangent',
    parallel: 'zds.toolbar.sketch.parallel',
    perpendicular: 'zds.toolbar.sketch.perpendicular',
    equal: 'zds.toolbar.sketch.equal',
    symmetric: 'zds.toolbar.sketch.symmetric',
    vertical: 'zds.toolbar.sketch.vertical',
    horizontal: 'zds.toolbar.sketch.horizontal',
    fixed: 'zds.toolbar.sketch.fixed',
    dimension: 'zds.toolbar.sketch.dimension',
    horizontalDistance: 'zds.toolbar.sketch.horizontalDistance',
    verticalDistance: 'zds.toolbar.sketch.verticalDistance',
    construction: 'zds.toolbar.sketch.construction',
  },
} as const
