@settings(defaultLengthUnit = mm)

sketch001 = startSketchOn(XY)
cubeMm = startProfile(sketch001, at = [10, 10])
  |> xLine(length = 5)
  |> yLine(length = -5)
  |> xLine(length = -5)
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
  |> extrude(%, length = 5)
