wall_thickness = 0.125
back_walls_width = 2
front_walls_width = 2.5
height = 5.5
filletRadius = 0.050
back_length = 7
exit_height = 1
front_length = 6
Fx = 0.5
Fy = 0.5

sketch001 = startSketchOn('-YZ')
  |> startProfileAt([back_walls_width / 2, 0], %)
  |> xLine(wall_thickness / 2, %)
  |> angledLineToX({ angle = 45, to = back_walls_width }, %, $seg01)
  |> yLineTo(height, %)
  |> xLine(-wall_thickness, %)
  |> yLineTo(segEndY(seg01), %)
  |> angledLineToX({
       angle = 45,
       to = back_walls_width / 2 + wall_thickness / 2
     }, %)
  |> xLine(-wall_thickness, %)
  |> angledLineToX({
       angle = 180 - 45,
       to = wall_thickness
     }, %)
  |> yLineTo(height, %)
  |> xLineTo(0, %)
  |> yLineTo(segEndY(seg01), %)
  |> angledLineToY({ angle = 180 - 45, to = 0 }, %)
  |> close(%)
part001 = revolve({
  angle = 90,
  axis = {
    custom = {
      axis = [1.0, 0.0],
      origin = [0.0, height + .0000001]
    }
  }
}, sketch001)

sketch002 = startSketchOn('-YZ')
  |> startProfileAt([back_walls_width / 2, 0], %)
  |> xLine(wall_thickness / 2, %)
  |> angledLineToX({ angle = 45, to = back_walls_width }, %, $seg02)
  |> yLineTo(height, %)
  |> xLine(-wall_thickness, %)
  |> yLineTo(segEndY(seg01), %)
  |> angledLineToX({
       angle = 45,
       to = back_walls_width / 2 + wall_thickness / 2
     }, %)
  |> xLine(-wall_thickness, %)
  |> angledLineToX({
       angle = 180 - 45,
       to = wall_thickness
     }, %)
  |> yLineTo(height, %)
  |> xLineTo(0, %)
  |> yLineTo(segEndY(seg02), %)
  |> angledLineToY({ angle = 180 - 45, to = 0 }, %)
  |> close(%)
  |> extrude(back_length - height, %)
