@settings(defaultLengthUnit = inch)

import "bolt.kcl"

export thickness = 4

startSketchOn(XY)
  |> circle(center = [5, 5], radius = 10)
  |> extrude(length = 10)
