name: Bug Report
description: File a bug report for the Zoo Modeling App
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to report a bug. Please provide as much information as possible to help us resolve it."

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "Explain the bug..."
    validations:
      required: true

  - type: textarea
    id: reproduce-bug
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Description of what you expected to happen.
      placeholder: "I expected that..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots and Recordings 
      description: If applicable, add screenshots to help explain your problem. Maximum upload size is 10MB.
      placeholder: "You can attach images or video recordings here."
    validations:
      required: false

  - type: input
    id: desktop-os
    attributes:
      label: Desktop OS
      description: "Your operating system"
      placeholder: "example: Windows 10, MacOS Big Sur"
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: "If you are using the web version, please specify the browser you are using."
      placeholder: "example: Chrome, Safari"
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: "The version of the Zoo Modeling App you're using."
      placeholder: "example: v0.15.0. You can find this in the settings."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: "Anything else you want to add..."
    validations:
      required: false
