name: Release
description: Create a new release for the Zoo Design Studio
title: Cut release v1.?.?
labels: [release]
assignees: [${{ github.actor }}]
body:
  - type: markdown
    attributes:
      value: |
        > Instructions: https://github.com/KittyCAD/modeling-app/blob/main/CONTRIBUTING.md#shipping-releases

        ---

        # Manual Checklist

        Release builds URL: ???

        ## Windows via ???

        * [ ] Download the release build for this platform
        * [ ] Confirm the application opens (dismiss the updater)
        * [ ] Create a project with a basic Text-to-CAD prompt
        * [ ] Confirm the result is viewable in an engine stream
        * [ ] Open the application again and confirm the updater can downgrade

        ## macOS via ???

        * [ ] Download the release build for this platform
        * [ ] Confirm the application opens (dismiss the updater)
        * [ ] Create a project with a basic Text-to-CAD prompt
        * [ ] Confirm the result is viewable in an engine stream
        * [ ] Open the application again and confirm the updater can downgrade

        ## Linux via ???

        * [ ] Download the release build for this platform
        * [ ] Confirm the application opens (dismiss the updater)
        * [ ] Create a project with a basic Text-to-CAD prompt
        * [ ] Confirm the result is viewable in an engine stream
        * [ ] Open the application again and confirm the updater can downgrade
