test:
    uv pip install .[test]
    uv run pytest tests/tests.py

test-filter name:
    uv pip install .[test]
    uv run pytest tests/tests.py::{{name}}

setup-uv:
    uv python install
    uv venv .venv
    echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
    echo "$PWD/.venv/bin" >> $GITHUB_PATH

lint:
    uv run ruff check

fmt:
    uv run ruff format
