// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppTheme } from "./AppTheme";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * The settings for the theme of the app.
 */
export type AppearanceSettings = { 
/**
 * The overall theme of the app.
 */
theme?: AppTheme | null, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
