// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSettings } from "./AppearanceSettings";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Application wide settings.
 */
export type AppSettings = { 
/**
 * The settings for the appearance of the app.
 */
appearance?: AppearanceSettings | null, 
/**
 * When the user is idle, teardown the stream after some time.
 */
stream_idle_mode?: number | null, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
