// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { ApiObjectId } from "./FrontendApi";
import type { ModelingCmd, UnitLength } from "./ModelingCmd";
import type { NodePath } from "./NodePath";
import type { PlaneName } from "./PlaneName";
import type { SourceRange } from "./SourceRange";

export type Artifact = { "type": "compositeSolid" } & CompositeSolid | { "type": "plane" } & Plane | { "type": "path" } & Path | { "type": "segment" } & Segment | { "type": "solid2d" } & Solid2d | { "type": "primitiveFace" } & PrimitiveFace | { "type": "primitiveEdge" } & PrimitiveEdge | { "type": "planeOfFace" } & PlaneOfFace | { "type": "startSketchOnFace" } & StartSketchOnFace | { "type": "startSketchOnPlane" } & StartSketchOnPlane | { "type": "sketchBlock" } & SketchBlock | { "type": "sketchBlockConstraint" } & SketchBlockConstraint | { "type": "sweep" } & Sweep | { "type": "wall" } & Wall | { "type": "cap" } & Cap | { "type": "sweepEdge" } & SweepEdge | { "type": "edgeCut" } & EdgeCut | { "type": "edgeCutEdge" } & EdgeCutEdge | { "type": "helix" } & Helix | { "type": "importedGeometry" } & ImportedGeometryArtifact | { "type": "gdtAnnotation" } & GdtAnnotationArtifact | { "type": "namedView" } & NamedViewArtifact | { "type": "pattern" } & Pattern;

/**
 * Where a named view's camera looks from: one variant per KCL constructor
 * function, so a stored view can never carry both a curated orientation and a
 * custom direction.
 */
export type ArtifactCameraLook = { "type": "oriented", orientation: ArtifactOrientation, } | { "type": "directed", direction: ArtifactPoint3d, up: ArtifactPoint3d, };

/**
 * API-owned camera intent used by named-view artifacts. It mirrors kcl-lib's
 * `CameraView` JSON shape while keeping kcl-api independent of execution
 * internals, as [`ArtifactPlaneInfo`] does for planes.
 *
 * The values are intent, not a snapshot of engine camera state: an absent
 * field is resolved by whichever consumer activates the view. Every length is
 * in millimeters, converted when the view was constructed.
 */
export type ArtifactCameraView = { look: ArtifactCameraLook, 
/**
 * The point the camera looks at, in millimeters. Absent means: center on
 * the bounds of the model at activation.
 */
target: ArtifactPoint3d | null, 
/**
 * The distance from the camera to the target, in millimeters. Absent
 * means: fit the model at activation.
 */
distance: number | null, projection: ArtifactProjection, };

/**
 * A command that may create or update artifacts on the TS side.  Because
 * engine commands are batched, we don't have the response yet when these are
 * created.
 */
export type ArtifactCommand = { 
/**
 * Identifier of the command that can be matched with its response.
 */
cmdId: string, 
/**
 * The source range that's the boundary of calling the standard
 * library, not necessarily the true source range of the command.
 */
range: SourceRange, 
/**
 * The engine command.  Each artifact command is backed by an engine
 * command.  In the future, we may need to send information to the TS side
 * without an engine command, in which case, we would make this field
 * optional. Imported file commands retain paths and format but omit raw
 * file bytes after the command has been sent to the engine.
 */
command: ModelingCmd, 
/**
 * Whether this command should be omitted when deriving the semantic
 * artifact graph. Query-only commands can still be useful in command
 * snapshots without becoming frontend selection artifacts.
 */
omitFromGraph?: boolean, };

export type ArtifactGraph = { map: { [key in ArtifactId]: Artifact }, itemCount: number, };

/**
 * API-owned camera orientation used by named-view artifacts, equivalent to
 * the KCL enum `std::view::Orientation`. Keeping it here means the wire model
 * does not depend on kcl-lib's execution types.
 */
export type ArtifactOrientation = "front" | "back" | "left" | "right" | "top" | "bottom" | "isometric";

/**
 * API-owned plane data used by artifacts. It mirrors kcl-lib's evaluated
 * plane JSON shape while keeping kcl-api independent of execution internals.
 */
export type ArtifactPlaneInfo = { origin: ArtifactPoint3d, xAxis: ArtifactPoint3d, yAxis: ArtifactPoint3d, zAxis: ArtifactPoint3d, };

/**
 * API-owned point data used by artifact payloads so the wire model does not
 * depend on kcl-lib's execution geometry types.
 */
export type ArtifactPoint3d = { x: number, y: number, z: number, units: UnitLength | null, };

/**
 * API-owned camera projection used by named-view artifacts, equivalent to the
 * KCL enum `std::view::Projection`. See [`ArtifactOrientation`].
 */
export type ArtifactProjection = "orthographic" | "perspective";

/**
 * API-owned sweep method equivalent to the engine extrusion method, avoiding
 * a kcl-api dependency on kittycad-modeling-cmds.
 */
export type ArtifactSweepMethod = "new" | "merge";

/**
 * API-owned visibility baseline used by named-view artifacts, equivalent to
 * the KCL enum `std::view::Visibility`. `Show` means every object is visible
 * except those the view's hide list names; `Hide` means the reverse.
 */
export type ArtifactVisibility = "show" | "hide";

export type Cap = { id: ArtifactId, subType: CapSubType, edgeCutEdgeIds: Array<ArtifactId>, sweepId: ArtifactId, pathIds: Array<ArtifactId>, 
/**
 * This is for the sketch-on-face plane, not for the cap itself.  Traverse
 * to the extrude and/or segment to get the cap's code_ref.
 */
faceCodeRef: CodeRef, 
/**
 * The command ID that got the data for this cap. Used for stable sorting.
 */
cmdId: string, };

export type CapSubType = "start" | "end";

export type CodeRef = { range: SourceRange, nodePath: NodePath, pathToNode: Array<[string | number, string]>, };

export type CompositeSolid = { id: ArtifactId, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, subType: CompositeSolidSubType, 
/**
 * Index of this output in the expression result, for operations that
 * return multiple selectable bodies from one KCL variable.
 */
outputIndex?: number | null, 
/**
 * Constituent solids of the composite solid.
 */
solidIds: Array<ArtifactId>, 
/**
 * Tool solids used for asymmetric operations like subtract.
 */
toolIds: Array<ArtifactId>, codeRef: CodeRef, 
/**
 * This is the ID of the composite solid that this is part of, if any, as a
 * composite solid can be used as input for another composite solid.
 */
compositeSolidId?: ArtifactId | null, 
/**
 * Pattern operations that use this composite solid as their source.
 */
patternIds?: Array<ArtifactId>, };

export type CompositeSolidSubType = "intersect" | "subtract" | "split" | "union";

export type EdgeCut = { id: ArtifactId, subType: EdgeCutSubType, consumedEdgeId: ArtifactId, edgeIds: Array<ArtifactId>, surfaceId?: ArtifactId | null, codeRef: CodeRef, };

export type EdgeCutEdge = { id: ArtifactId, edgeCutId: ArtifactId, surfaceId: ArtifactId, };

export type EdgeCutSubType = "fillet" | "chamfer" | "custom";

export type GdtAnnotationArtifact = { id: ArtifactId, codeRef: CodeRef, };

export type Helix = { id: ArtifactId, 
/**
 * The axis of the helix.  Currently this is always an edge ID, but we may
 * add axes to the graph.
 */
axisId: ArtifactId | null, codeRef: CodeRef, 
/**
 * The sweep, if any, that this Helix serves as the trajectory for.
 */
trajectorySweepId: ArtifactId | null, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, };

export type ImportedGeometryArtifact = { id: ArtifactId, codeRef: CodeRef, };

/**
 * A named view declared in KCL by `view::named`: a display name, camera intent
 * and the objects the view shows or hides.
 *
 * The view is data for a consumer to activate later, so this artifact holds no
 * engine geometry and its creation sends no engine command. The objects are
 * named by ARTIFACT id, so a consumer resolves each one through the artifact
 * graph; an extruded solid's engine id differs from its artifact id, and the
 * translation belongs to whoever applies the view.
 */
export type NamedViewArtifact = { id: ArtifactId, 
/**
 * The display name the author gave the view. Required, and unique among
 * the views declared by the same module.
 */
name: string, camera: ArtifactCameraView, 
/**
 * Whether objects start visible or hidden, which decides which of the two
 * lists below can act.
 */
baseline: ArtifactVisibility, 
/**
 * Artifacts the view shows. Meaningful under a `Hide` baseline, where they
 * are the only visible objects.
 */
showIds: Array<ArtifactId>, 
/**
 * Artifacts the view hides. Meaningful under a `Show` baseline, where they
 * are the only hidden objects.
 */
hideIds: Array<ArtifactId>, codeRef: CodeRef, };

export type Path = { id: ArtifactId, subType: PathSubType, planeId: ArtifactId, segIds: Array<ArtifactId>, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, 
/**
 * The sweep, if any, that this Path serves as the base path for.
 * corresponds to `path_id` on the Sweep.
 */
sweepId?: ArtifactId | null, 
/**
 * The sweep, if any, that this Path serves as the trajectory for.
 */
trajectorySweepId: ArtifactId | null, solid2dId?: ArtifactId | null, codeRef: CodeRef, 
/**
 * This is the ID of the composite solid that this is part of, if any, as
 * this can be used as input for another composite solid.
 */
compositeSolidId?: ArtifactId | null, 
/**
 * For sketch paths, the ID of the sketch block this path was created
 * from. `None` for region paths and paths created in other ways.
 */
sketchBlockId?: ArtifactId | null, 
/**
 * For region paths, the ID of the sketch path this region was created
 * from. `None` for sketch paths.
 */
originPathId?: ArtifactId | null, 
/**
 * The hole, if any, from a subtract2d() call.
 */
innerPathId?: ArtifactId | null, 
/**
 * The `Path` that this is a hole of, if any. The inverse link of
 * `inner_path_id`.
 */
outerPathId?: ArtifactId | null, 
/**
 * Pattern operations that use this path as their source.
 */
patternIds?: Array<ArtifactId>, };

export type PathSubType = "sketch" | "region";

export type Pattern = { id: ArtifactId, subType: PatternSubType, 
/**
 * Geometry artifact that was the source of the pattern operation.
 */
sourceId: ArtifactId, 
/**
 * IDs of copied top-level objects created by the pattern operation.
 */
copyIds: Array<ArtifactId>, 
/**
 * IDs of copied faces created by the pattern operation.
 */
copyFaceIds: Array<ArtifactId>, 
/**
 * IDs of copied edges created by the pattern operation.
 */
copyEdgeIds: Array<ArtifactId>, codeRef: CodeRef, };

export type PatternSubType = "circular" | "linear" | "transform";

export type Plane = { id: ArtifactId, pathIds: Array<ArtifactId>, codeRef: CodeRef, };

export type PlaneOfFace = { id: ArtifactId, faceId: ArtifactId, codeRef: CodeRef, };

export type PrimitiveEdge = { id: ArtifactId, solidId: ArtifactId, codeRef: CodeRef, };

export type PrimitiveFace = { id: ArtifactId, solidId: ArtifactId, codeRef: CodeRef, };

export type Segment = { id: ArtifactId, pathId: ArtifactId, 
/**
 * The original segment this segment was cloned from, if any. For clones
 * of clones, this continues to point to the originating segment.
 */
sourceSegmentId?: ArtifactId | null, 
/**
 * If this artifact is a segment in a region, the segment in the original
 * sketch that this was derived from.
 */
originalSegId?: ArtifactId | null, surfaceId?: ArtifactId | null, edgeIds: Array<ArtifactId>, edgeCutId?: ArtifactId | null, codeRef: CodeRef, commonSurfaceIds: Array<ArtifactId>, };

export type SketchBlock = { id: ArtifactId, 
/**
 * The semantic standard plane name when the sketch block is on a standard plane.
 */
standardPlane?: PlaneName | null, 
/**
 * The concrete plane artifact ID backing the sketch block, when one is available.
 */
planeId?: ArtifactId | null, 
/**
 * The evaluated plane data backing the sketch block, when the sketch is on a plane.
 */
planeInfo?: ArtifactPlaneInfo | null, 
/**
 * The path artifact ID created from the sketch block, if there is one.
 * There are edge cases when a path isn't created, like when there are no
 * segments.
 */
pathId?: ArtifactId | null, codeRef: CodeRef, 
/**
 * The sketch ID (ObjectId) for the sketch scene object.
 */
sketchId: ApiObjectId, };

export type SketchBlockConstraint = { id: ArtifactId, 
/**
 * The sketch ID (ObjectId) that owns this constraint.
 */
sketchId: ApiObjectId, 
/**
 * The constraint ID (ObjectId) for the constraint scene object.
 */
constraintId: ApiObjectId, constraintType: SketchBlockConstraintType, codeRef: CodeRef, };

export type SketchBlockConstraintType = "angle" | "coincident" | "distance" | "diameter" | "equalRadius" | "fixed" | "horizontalDistance" | "verticalDistance" | "horizontal" | "linesEqualLength" | "midpoint" | "parallel" | "perpendicular" | "radius" | "symmetric" | "tangent" | "vertical";

export type Solid2d = { id: ArtifactId, pathId: ArtifactId, };

export type StartSketchOnFace = { id: ArtifactId, faceId: ArtifactId, codeRef: CodeRef, };

export type StartSketchOnPlane = { id: ArtifactId, planeId: ArtifactId, codeRef: CodeRef, };

/**
 * A sweep is a more generic term for extrude, revolve, loft, sweep, and blend.
 */
export type Sweep = { id: ArtifactId, subType: SweepSubType, pathId: ArtifactId, surfaceIds: Array<ArtifactId>, edgeIds: Array<ArtifactId>, codeRef: CodeRef, 
/**
 * The original sweep this body was cloned from, if any. For clones of
 * clones, this continues to point to the originating sweep.
 */
sourceSweepId?: ArtifactId | null, 
/**
 * ID of trajectory path for sweep, if any
 * Only applicable to SweepSubType::Sweep and SweepSubType::Blend, which
 * can use a second path-like input
 */
trajectoryId: ArtifactId | null, method: ArtifactSweepMethod, 
/**
 * Whether this artifact has been used in a subsequent operation
 */
consumed: boolean, 
/**
 * Pattern operations that use this sweep as their source.
 */
patternIds?: Array<ArtifactId>, };

export type SweepEdge = { id: ArtifactId, subType: SweepEdgeSubType, segId: ArtifactId, cmdId: string, sweepId: ArtifactId, commonSurfaceIds: Array<ArtifactId>, };

export type SweepEdgeSubType = "opposite" | "adjacent" | "previousAdjacent";

export type SweepSubType = "extrusion" | "extrusionTwist" | "revolve" | "revolveAboutEdge" | "loft" | "blend" | "sweep";

export type Wall = { id: ArtifactId, segId: ArtifactId, edgeCutEdgeIds: Array<ArtifactId>, sweepId: ArtifactId, pathIds: Array<ArtifactId>, 
/**
 * This is for the sketch-on-face plane, not for the wall itself.  Traverse
 * to the extrude and/or segment to get the wall's code_ref.
 */
faceCodeRef: CodeRef, 
/**
 * The command ID that got the data for this wall. Used for stable sorting.
 */
cmdId: string, };
