// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeoMetaView } from "./GeoMetaView";
import type { UnitLength } from "./ModelingCmd";
import type { TagDeclarator } from "./TagDeclarator";

export type BasePathView = { from: [number, number], to: [number, number], units: UnitLength, tag: TagDeclarator | null, __geoMeta: GeoMetaView, };
