// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnresolvedEdgeSpecifier } from "./UnresolvedEdgeSpecifier";

/**
 * A bounded edge.
 * Carries either `edge_id` (resolved) or `edge_specifier` (payload passed through for resolution in blend).
 */
export type BoundedEdge = { 
/**
 * The id of the face this edge belongs to.
 */
faceId: string, 
/**
 * The id of the edge (when resolved from a tag or UUID). Mutually exclusive with `edge_specifier`.
 */
edgeId: string | null, 
/**
 * Edge specifier payload (sideFaces, endFaces, index) when not resolved. Resolved in blend().
 */
edgeSpecifier: UnresolvedEdgeSpecifier | null, 
/**
 * A percentage bound of the edge, used to restrict what portion of the edge will be used.
 * Range (0, 1)
 */
lowerBound: number, 
/**
 * A percentage bound of the edge, used to restrict what portion of the edge will be used.
 * Range (0, 1)
 */
upperBound: number, };
