// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Orientation } from "./Orientation";
import type { Point3d } from "./Point3d";

/**
 * Where the camera looks from: one variant per constructor function, so a
 * value can never carry both a curated orientation and a custom direction.
 */
export type CameraLook = { "type": "oriented", orientation: Orientation, } | { "type": "directed", direction: Point3d, up: Point3d, };
