// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sketch } from "./Sketch";

export type CreatorFace = { 
/**
 * The face id that served as the base.
 */
face_id: string, 
/**
 * The solid id that owned the face.
 */
solid_id: string, 
/**
 * The sketch used for the operation.
 */
sketch: Sketch, };
