// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One tag entry in a fillet/chamfer call that used `tags` directly (for refactor to edgeRefs).
 */
export type DirectTagFilletTagEntry = { tagIdentifier: string, edgeId: string, faceIds: [string, string], };
