// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EdgeRefactorStdlibFn } from "./EdgeRefactorStdlibFn";
import type { SourceRange } from "./SourceRange";

/**
 * Metadata collected when a deprecated edge stdlib function runs, for refactor-to-edgeRefs lint/code mod.
 */
export type EdgeRefactorMeta = { edgeId: string, faceIds: [string, string], endFaceIds?: Array<string>, sourceRange: SourceRange, stdlibFn: EdgeRefactorStdlibFn, };
