// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which stdlib edge function produced this refactor metadata (for lint/code mod).
 */
export type EdgeRefactorStdlibFn = "getOppositeEdge" | "getNextAdjacentEdge" | "getPreviousAdjacentEdge" | "getCommonEdge" | "edgeId";
