// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumericValueView } from "./NumericValueView";
import type { TagDeclaratorView } from "./TagDeclaratorView";

export type EdgeCutView = { "type": "fillet", id: string, radius: NumericValueView, edgeId: string, tag: TagDeclaratorView | null, } | { "type": "chamfer", id: string, length: NumericValueView, edgeId: string, tag: TagDeclaratorView | null, };
