// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagDeclarator } from "./TagDeclarator";

export type EdgeCutView = { "type": "fillet", id: string, edge_id: string, tag: TagDeclarator | null, } | { "type": "chamfer", id: string, edge_id: string, tag: TagDeclarator | null, };
