// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { Node } from "./Node";

/**
 * A single nullary enum variant, e.g. `| Red`.
 */
export type EnumVariant = { "type": "EnumVariant", name: Node<Identifier>, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
