// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactGraph } from "./Artifact";
import type { CompilationIssue } from "./CompilationIssue";
import type { DefaultPlanes } from "./DefaultPlanes";
import type { KclValueView } from "./KclValueView";
import type { ModuleId } from "./ModuleId";
import type { ModulePath } from "./ModulePath";
import type { OperationsByModule } from "./OperationsByModule";
import type { RefactorMetadata } from "./RefactorMetadata";

/**
 * Outcome of executing a program.  This is used in TS.
 */
export type ExecOutcome = { 
/**
 * Variables in the top-level of the root module. Note that functions will have an invalid env ref.
 */
variables: { [key in string]: KclValueView }, 
/**
 * Operations that have been performed in execution order, grouped by
 * owning module id, for display in the Feature Tree.
 */
operations: OperationsByModule, 
/**
 * Output artifact graph.
 */
artifactGraph: ArtifactGraph, 
/**
 * Execution-backed metadata used by Z0006 and future auto-refactors.
 */
refactorMetadata: Array<RefactorMetadata>, 
/**
 * Non-fatal errors and warnings.
 */
issues: Array<CompilationIssue>, 
/**
 * File Names in module Id array index order
 */
filenames: { [key in ModuleId]: ModulePath }, 
/**
 * The default planes.
 */
defaultPlanes: DefaultPlanes | null, };
