// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SurfaceView } from "./SurfaceView";

export type ExtrudeSurfaceView = { "type": "extrudePlane" } & SurfaceView | { "type": "extrudeArc" } & SurfaceView | { "type": "chamfer" } & SurfaceView | { "type": "fillet" } & SurfaceView;
