// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { FaceParentSolidView } from "./FaceParentSolidView";
import type { ApiObjectId } from "./FrontendApi";
import type { UnitLength } from "./ModelingCmd";
import type { Point3dView } from "./Point3dView";

export type FaceView = { id: string, artifactId: ArtifactId, objectId: ApiObjectId, value: string, xAxis: Point3dView, yAxis: Point3dView, parentSolid: FaceParentSolidView, units: UnitLength, };
