// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProfileClosed } from "./ProfileClosed";

/**
 * The limited subset of a face's parent solid needed by face-backed sketches.
 */
export type FaceParentSolid = { 
/**
 * Which solid does this face belong to?
 */
solidId: string, 
/**
 * ID of the sketch which created this solid, if any.
 */
creatorSketchId: string | null, 
/**
 * Has the creator sketch been closed? This is only relevant if `creator_sketch_id` is Some, and we cannot infer the closed status otherwise.
 */
creatorSketchIsClosed: ProfileClosed | null, 
/**
 * Pending edge cut IDs that may need to be flushed before referencing the face.
 */
edgeCutIds?: Array<string>, };
