// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Abstract lint problem type.
 */
export type FindingFamily = "style" | "correctness" | "simplify";
