// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumericSuffix } from "./NumericSuffix";

export type ApiObjectId = number;

export type ApiPoint2d<U> = { x: U, y: U, };

export type ArcCtor = { start: ApiPoint2d<Expr>, end: ApiPoint2d<Expr>, center: ApiPoint2d<Expr>, 
/**
 * The direction that the arc sweeps from start to end. `None` means it
 * wasn't written in the source, which defaults to counterclockwise.
 */
direction?: ArcDirection, construction?: boolean, };

/**
 * The direction that an arc sweeps from its start point to its end point.
 */
export type ArcDirection = "ccw" | "cw";

export type CircleCtor = { start: ApiPoint2d<Expr>, center: ApiPoint2d<Expr>, construction?: boolean, };

export type ControlPointSplineCtor = { points: Array<ApiPoint2d<Expr>>, construction?: boolean, };

export type Expr = { "type": "Number" } & Number | { "type": "Var" } & Number | { "type": "Variable" } & string;

export type Freedom = "Free" | "Fixed" | "Conflict";

export type LineCtor = { start: ApiPoint2d<Expr>, end: ApiPoint2d<Expr>, construction?: boolean, };

export type Number = { value: number, units: NumericSuffix, };

export type PointCtor = { position: ApiPoint2d<Expr>, };
