// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { ExecOutcome } from "./ExecOutcome";
import type { ExecutorSettings } from "./ExecutorSettings";
import type { KclErrorWithOutputs } from "./KclErrorWithOutputs";
import type { NodePath } from "./NodePath";
import type { NumericSuffix } from "./NumericSuffix";
import type { PlaneName } from "./PlaneName";
import type { SketchCheckpointId } from "./SketchCheckpointId";
import type { SourceRange } from "./SourceRange";

export type Angle = { lines: Array<ApiObjectId>, angle: Number, source: ConstraintSource, };

export type ApiArc = { start: ApiObjectId, end: ApiObjectId, center: ApiObjectId, ctor: SegmentCtor, ctor_applicable: boolean, construction: boolean, };

export type ApiCap = { id: ApiObjectId, kind: ApiCapKind, source: ApiCapSource, solidOutputIndex?: number, };

export type ApiCapKind = "start" | "end";

export type ApiCapSource = { solid: ApiSourceRefRange, sweep: ApiSourceRefRange, };

export type ApiCircle = { start: ApiObjectId, center: ApiObjectId, ctor: SegmentCtor, ctor_applicable: boolean, construction: boolean, };

export type ApiConstraint = { "type": "Coincident" } & Coincident | { "type": "Distance" } & Distance | { "type": "Angle" } & Angle | { "type": "Diameter" } & Diameter | { "type": "EqualRadius" } & EqualRadius | { "type": "Fixed" } & Fixed | { "type": "HorizontalDistance" } & Distance | { "type": "VerticalDistance" } & Distance | { "type": "Horizontal" } & Horizontal | { "type": "LinesEqualLength" } & LinesEqualLength | { "type": "Midpoint" } & Midpoint | { "type": "Parallel" } & Parallel | { "type": "Perpendicular" } & Perpendicular | { "type": "Radius" } & Radius | { "type": "Symmetric" } & Symmetric | { "type": "Tangent" } & Tangent | { "type": "Vertical" } & Vertical;

export type ApiControlPointSpline = { controls: Array<ApiObjectId>, degree: number, ctor: SegmentCtor, ctor_applicable: boolean, construction: boolean, };

export type ApiFace = { id: ApiObjectId, };

export type ApiFile = { id: ApiFileId, path: string, text: string, };

export type ApiFileId = number;

export type ApiLine = { start: ApiObjectId, end: ApiObjectId, owner?: ApiObjectId, ctor: SegmentCtor, ctor_applicable: boolean, construction: boolean, };

export type ApiObject = { id: ApiObjectId, kind: ApiObjectKind, label: string, comments: string, artifact_id: ArtifactId, source: ApiSourceRef, };

export type ApiObjectId = number;

export type ApiObjectKind = { "type": "Nil" } | { "type": "Plane" } & ApiPlane | { "type": "Face" } & ApiFace | { "type": "Wall" } & ApiWall | { "type": "Cap" } & ApiCap | { "type": "Sketch" } & ApiSketch | { "type": "Segment", segment: ApiSegment, } | { "type": "Constraint", constraint: ApiConstraint, };

export type ApiPlane = { "object": ApiObjectId } | { "default": PlaneName };

export type ApiPoint = { position: ApiPoint2d<Number>, ctor: PointCtor | null, owner: ApiObjectId | null, freedom: Freedom, constraints: Array<ApiObjectId>, };

export type ApiPoint2d<U> = { x: U, y: U, };

export type ApiProjectId = number;

export type ApiSegment = { "type": "Point" } & ApiPoint | { "type": "Line" } & ApiLine | { "type": "Arc" } & ApiArc | { "type": "Circle" } & ApiCircle | { "type": "ControlPointSpline" } & ApiControlPointSpline;

export type ApiSketch = { args: SketchCtor, plane: ApiObjectId, segments: Array<ApiObjectId>, constraints: Array<ApiObjectId>, };

export type ApiSourceRef = { "type": "Simple", range: SourceRange, node_path: NodePath | null, } | { "type": "BackTrace", ranges: Array<[SourceRange, NodePath | null]>, };

export type ApiSourceRefRange = { range: SourceRange, nodePath: NodePath | null, };

export type ApiStartOrEnd<T> = { "type": "Start" } & T | { "type": "End" } & T;

export type ApiVersion = number;

export type ApiWall = { id: ApiObjectId, source: ApiWallSource, solidOutputIndex?: number, };

export type ApiWallSource = { solid: ApiSourceRefRange, sweep: ApiSourceRefRange, path?: ApiSourceRefRange, segment: ApiSourceRefRange, };

export type ArcCtor = { start: ApiPoint2d<Expr>, end: ApiPoint2d<Expr>, center: ApiPoint2d<Expr>, construction?: boolean, };

export type CircleCtor = { start: ApiPoint2d<Expr>, center: ApiPoint2d<Expr>, construction?: boolean, };

export type Coincident = { segments: Array<ConstraintSegment>, };

export type ConstraintSegment = ApiObjectId | OriginLiteral;

export type ConstraintSource = { expr: string, is_literal: boolean, };

export type ControlPointSplineCtor = { points: Array<ApiPoint2d<Expr>>, construction?: boolean, };

export type Diameter = { arc: ApiObjectId, diameter: Number, labelPosition?: ApiPoint2d<Number>, source: ConstraintSource, };

export type Distance = { points: Array<ConstraintSegment>, distance: Number, labelPosition?: ApiPoint2d<Number>, source: ConstraintSource, };

export type EditSketchOutcome = { sceneGraphDelta: SceneGraphDelta, checkpointId: SketchCheckpointId | null, };

export type EqualRadius = { input: Array<ApiObjectId>, };

export type Error = { msg: string, };

export type ExistingSegmentCtor = { id: ApiObjectId, ctor: SegmentCtor, };

export type Expr = { "type": "Number" } & Number | { "type": "Var" } & Number | { "type": "Variable" } & string;

/**
 * Multiple fixed constraints, allowing callers to add fixed constraints on
 * multiple points at once.
 */
export type Fixed = { points: Array<FixedPoint>, };

/**
 * A fixed constraint on a single point.
 */
export type FixedPoint = { point: ApiObjectId, position: ApiPoint2d<Number>, };

export type Freedom = "Free" | "Fixed" | "Conflict";

export type Horizontal = { line: ApiObjectId, } | { points: Array<ConstraintSegment>, };

export type IgnoreMe = { a: ApiFile, };

export type LineCtor = { start: ApiPoint2d<Expr>, end: ApiPoint2d<Expr>, construction?: boolean, };

export type LinesEqualLength = { lines: Array<ApiObjectId>, };

export type Midpoint = { point: ConstraintSegment, segment: ApiObjectId, };

export type NewSketchOutcome = { sourceDelta: SourceDelta, sceneGraphDelta: SceneGraphDelta, sketchId: ApiObjectId, checkpointId: SketchCheckpointId | null, };

export type Number = { value: number, units: NumericSuffix, };

export type OriginLiteral = "ORIGIN";

export type Parallel = { lines: Array<ApiObjectId>, };

export type Perpendicular = { lines: Array<ApiObjectId>, };

export type PointCtor = { position: ApiPoint2d<Expr>, };

export type Radius = { arc: ApiObjectId, radius: Number, labelPosition?: ApiPoint2d<Number>, source: ConstraintSource, };

export type RestoreSketchCheckpointOutcome = { sourceDelta: SourceDelta, sceneGraphDelta: SceneGraphDelta, };

export type SceneGraph = { project: ApiProjectId, file: ApiFileId, version: ApiVersion, objects: Array<ApiObject>, settings: ExecutorSettings, sketch_mode: ApiObjectId | null, };

export type SceneGraphDelta = { new_graph: SceneGraph, new_objects: Array<ApiObjectId>, invalidates_ids: boolean, exec_outcome: ExecOutcome, };

export type SegmentCtor = { "type": "Point" } & PointCtor | { "type": "Line" } & LineCtor | { "type": "Arc" } & ArcCtor | { "type": "Circle" } & CircleCtor | { "type": "ControlPointSpline" } & ControlPointSplineCtor;

export type SegmentDragAnchor = { segmentId: ApiObjectId, target: ApiPoint2d<Number>, };

export type SetProgramOutcome = { "type": "Success", sceneGraph: SceneGraph, execOutcome: ExecOutcome, checkpointId: SketchCheckpointId | null, } | { "type": "ExecFailure", error: KclErrorWithOutputs, };

/**
 * Arguments for creating a new sketch. This is similar to the constructor of
 * other kinds of objects in that it is the inputs to the sketch, not the
 * outputs.
 */
export type SketchCtor = { 
/**
 * The sketch surface.
 */
on: ApiPlane, };

export type SketchMutationOutcome = { sourceDelta: SourceDelta, sceneGraphDelta: SceneGraphDelta, checkpointId: SketchCheckpointId | null, };

export type SourceDelta = { text: string, };

export type Symmetric = { input: Array<ApiObjectId>, axis: ApiObjectId, };

export type Tangent = { input: Array<ApiObjectId>, };

export type Vertical = { line: ApiObjectId, } | { points: Array<ConstraintSegment>, };
