// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A GD&T annotation.
 */
export type GdtAnnotation = { "type": "GdtAnnotation", 
/**
 * The engine ID.
 */
id: string, };
