// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObjectId, ArcCtor, ArcDirection, CircleCtor, ControlPointSplineCtor, Freedom, LineCtor, PointCtor } from "./FrontendApi";
import type { Sketch } from "./Sketch";
import type { SketchSurface } from "./SketchSurface";
import type { Solid } from "./Solid";
import type { TagIdentifier } from "./TagIdentifier";
import type { TyF64 } from "./TyF64";

/**
 * A geometry.
 */
export type Geometry = { "type": "Sketch" } & Sketch | { "type": "Solid" } & Solid;

export type Segment = { 
/**
 * The engine ID.
 */
id: string, objectId: ApiObjectId, kind: SegmentKind, surface: SketchSurface, 
/**
 * The engine ID of the sketch that this is a part of.
 */
sketchId: string, tag: TagIdentifier | null, };

export type SegmentKind = { "point": { position: [TyF64, TyF64], ctor: PointCtor, freedom: Freedom | null, } } | { "line": { start: [TyF64, TyF64], end: [TyF64, TyF64], ctor: LineCtor, start_object_id: ApiObjectId, end_object_id: ApiObjectId, start_freedom: Freedom | null, end_freedom: Freedom | null, construction: boolean, } } | { "arc": { start: [TyF64, TyF64], end: [TyF64, TyF64], center: [TyF64, TyF64], ctor: ArcCtor, start_object_id: ApiObjectId, end_object_id: ApiObjectId, center_object_id: ApiObjectId, start_freedom: Freedom | null, end_freedom: Freedom | null, center_freedom: Freedom | null, 
/**
 * The direction that the arc sweeps from its declared start to its
 * declared end.
 */
direction?: ArcDirection, construction: boolean, } } | { "circle": { start: [TyF64, TyF64], center: [TyF64, TyF64], ctor: CircleCtor, start_object_id: ApiObjectId, center_object_id: ApiObjectId, start_freedom: Freedom | null, center_freedom: Freedom | null, construction: boolean, } } | { "controlPointSpline": { controls: Array<[TyF64, TyF64]>, ctor: ControlPointSplineCtor, control_object_ids: Array<ApiObjectId>, control_polygon_edge_object_ids: Array<ApiObjectId>, control_freedoms: Array<Freedom | null>, degree: number, construction: boolean, } };
