// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { UnitLength } from "./ModelingCmd";

export type HelixView = { value: string, artifactId: ArtifactId, revolutions: number, angleStart: number, ccw: boolean, cylinderId: string | null, units: UnitLength, };
