// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFlag } from "./RuntimeFlag";

/**
 * Maps 1-1 to the KCL related flags added to the Admin portal and TS.
 *
 * Fields missing from a deserialized payload become [`RuntimeFlag::Unset`],
 * so a sender built before a flag existed falls back to Rust-side defaults
 * instead of failing to parse.
 *
 * `use_new_parser` is a placeholder while the new parser is being implemented:
 *
 * - It has no corresponding Admin portal flag yet.
 * - It defaults to [`RuntimeFlag::Off`] when omitted.
 * - The current parser does not read it.
 */
export type KclRuntimeFlags = { use_new_lexer_parser: RuntimeFlag, use_new_parser: RuntimeFlag, };
