// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuntimeFlag } from "./RuntimeFlag";

/**
 * Maps 1-1 to the KCL related flags added to the Admin portal and TS.
 */
export type KclRuntimeFlags = { use_new_lexer_parser: RuntimeFlag, };
