// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundedEdge } from "./BoundedEdge";
import type { CameraView } from "./CameraView";
import type { Face } from "./Face";
import type { GdtAnnotation } from "./GdtAnnotation";
import type { AbstractSegment, SketchConstraint, SketchVar } from "./Geometry";
import type { Helix } from "./Helix";
import type { ImportedGeometry } from "./ImportedGeometry";
import type { KclNone } from "./KclNone";
import type { ModuleId } from "./ModuleId";
import type { NamedViewValue } from "./NamedViewValue";
import type { Node } from "./Node";
import type { NumericType } from "./NumericType";
import type { Plane } from "./Plane";
import type { Sketch } from "./Sketch";
import type { Solid } from "./Solid";
import type { TagDeclarator } from "./TagDeclarator";
import type { TagIdentifier } from "./TagIdentifier";

/**
 * Any KCL value.
 */
export type KclValueView = { "type": "Uuid", value: string, } | { "type": "Bool", value: boolean, } | { "type": "Number", value: number, ty: NumericType, } | { "type": "String", value: string, } | { "type": "Enum", enum_name: string, variant: string, } | { "type": "SketchVar", value: SketchVar, } | { "type": "SketchConstraint", value: SketchConstraint, } | { "type": "Tuple", value: Array<KclValueView>, } | { "type": "HomArray", value: Array<KclValueView>, } | { "type": "Object", value: { [key in string]: KclValueView }, constrainable: boolean, } | { "type": "TagIdentifier" } & TagIdentifier | { "type": "TagDeclarator" } & Node<TagDeclarator> | { "type": "GdtAnnotation", value: GdtAnnotation, } | { "type": "CameraView", value: CameraView, } | { "type": "NamedView", value: NamedViewValue, } | { "type": "Plane", value: Plane, } | { "type": "Face", value: Face, } | { "type": "BoundedEdge", value: BoundedEdge, } | { "type": "Segment", value: AbstractSegment, } | { "type": "Sketch", value: Sketch, } | { "type": "Solid", value: Solid, } | { "type": "Helix", value: Helix, } | { "type": "ImportedGeometry" } & ImportedGeometry | { "type": "Function", } | { "type": "Module", value: ModuleId, } | { "type": "KclNone", value: KclNone, };
