// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundedEdgeView } from "./BoundedEdgeView";
import type { FaceView } from "./FaceView";
import type { GdtAnnotationView } from "./GdtAnnotationView";
import type { HelixView } from "./HelixView";
import type { ImportedGeometryView } from "./ImportedGeometryView";
import type { ModuleId } from "./ModuleId";
import type { NumericType } from "./NumericType";
import type { PlaneView } from "./PlaneView";
import type { SketchVarView } from "./SketchVarView";
import type { SketchView } from "./SketchView";
import type { SolidView } from "./SolidView";
import type { TagIdentifierView } from "./TagIdentifierView";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A serializable, presentational view of any KCL value.
 *
 * This type deliberately contains no executor state. Runtime values are
 * converted to it by `kcl-lib` before they cross an API boundary.
 */
export type KclValueView = { "type": "Uuid", value: string, } | { "type": "Bool", value: boolean, } | { "type": "Number", value: number, ty: NumericType, } | { "type": "String", value: string, } | { "type": "Enum", enum_name: string, variant: string, } | { "type": "SketchVar", value: SketchVarView, } | { "type": "SketchConstraint", value: JsonValue, } | { "type": "Tuple", value: Array<KclValueView>, } | { "type": "HomArray", value: Array<KclValueView>, } | { "type": "Object", value: { [key in string]: KclValueView }, constrainable: boolean, } | { "type": "TagIdentifier" } & TagIdentifierView | { "type": "TagDeclarator", value: string, } | { "type": "GdtAnnotation", value: GdtAnnotationView, } | { "type": "CameraView", value: JsonValue, } | { "type": "NamedView", value: JsonValue, } | { "type": "Plane", value: PlaneView, } | { "type": "Face", value: FaceView, } | { "type": "BoundedEdge", value: BoundedEdgeView, } | { "type": "Segment", value: JsonValue, } | { "type": "Sketch", value: SketchView, } | { "type": "Solid", value: SolidView, } | { "type": "Helix", value: HelixView, } | { "type": "ImportedGeometry" } & ImportedGeometryView | { "type": "Function", } | { "type": "Module", value: ModuleId, } | { "type": "Type", experimental: boolean, } | { "type": "KclNone", };
