// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackfaceDefault } from "./BackfaceDefault";
import type { CameraOrbitType } from "./CameraOrbitType";
import type { CameraProjectionType } from "./CameraProjectionType";
import type { DefaultTrue } from "./DefaultTrue";
import type { LengthDefaultMm } from "./LengthDefaultMm";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Settings that affect the behavior while modeling.
 */
export type ModelingSettings = { 
/**
 * The default unit to use in modeling dimensions.
 * If not given, defaults to millimeters.
 */
base_unit?: LengthDefaultMm | null, 
/**
 * The projection mode the camera should use while modeling.
 */
camera_projection?: CameraProjectionType | null, 
/**
 * The methodology the camera should use to orbit around the model.
 */
camera_orbit?: CameraOrbitType | null, 
/**
 * Highlight edges of 3D objects?
 */
highlight_edges?: DefaultTrue | null, 
/**
 * Whether or not Screen Space Ambient Occlusion (SSAO) is enabled.
 */
enable_ssao?: DefaultTrue | null, 
/**
 * The default color to use for surface backfaces.
 */
backface_color?: BackfaceDefault | null, 
/**
 * Whether or not to show a scale grid in the 3D modeling view
 */
show_scale_grid?: boolean | null, 
/**
 * When enabled, the grid will use a fixed size based on your selected units rather than automatically scaling with zoom level.
 * If true, the grid cells will be fixed-size, where the width is your default length unit.
 * If false, the grid will get larger as you zoom out, and smaller as you zoom in.
 */
fixed_size_grid?: DefaultTrue | null, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
