// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The valid types of angle formats.
 */
export type UnitAngle = "degrees" | "radians";

/**
 * The valid types of length units.
 */
export type UnitLength = "cm" | "ft" | "in" | "m" | "mm" | "yd";
