// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { CameraView } from "./CameraView";
import type { Visibility } from "./Visibility";

/**
 * A named view: a display name, a camera and the visibility the author
 * declared.
 *
 * The value keeps the form the author wrote -- one `baseline` and one
 * exception list -- rather than the artifact's pair of lists, so a value
 * cannot carry an exception for `Show` and an exception for `Hide` at the
 * same time. `view::named` splits `except_ids` into the artifact's `show_ids`
 * and `hide_ids` when it registers the view.
 *
 * Fields stay private for the reason [`CameraView`]'s do: a value is only
 * produced by `view::named`, which checks the name before building one.
 */
export type NamedViewValue = { 
/**
 * The artifact this view was registered as. A consumer holding the value
 * finds the view in the artifact graph under this id.
 */
artifactId: ArtifactId, 
/**
 * The display name the author gave the view.
 */
name: string, camera: CameraView, 
/**
 * Whether the view's objects start visible or hidden.
 */
baseline: Visibility, 
/**
 * The exception to the baseline, as artifact ids: the hidden objects
 * under a `Show` baseline, and the only visible objects under `Hide`. An
 * empty list excepts nothing, so everything is visible under `Show` and
 * nothing is visible under `Hide`.
 */
exceptIds: Array<ArtifactId>, };
