// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A standard camera orientation.
 *
 * Rust mirror of the KCL enum `std::view::Orientation`. Serialized variant
 * names match the KCL spellings exactly.
 */
export type Orientation = "Front" | "Back" | "Left" | "Right" | "Top" | "Bottom" | "Isometric";
