// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultParamVal } from "./DefaultParamVal";
import type { Identifier } from "./Identifier";
import type { Node } from "./Node";
import type { Type } from "./Type";
import type { VersionConstraint } from "./VersionConstraint";

/**
 * Parameter of a KCL function.
 */
export type Parameter = { "type": "Parameter", 
/**
 * Whether it's experimental.
 */
experimental?: boolean, 
/**
 * If true, this parameter is deprecated regardless of the KCL version. Use
 * `deprecated_since` instead to deprecate the parameter only at or after a
 * particular version. At most one of the two may be set.
 */
deprecated?: boolean, 
/**
 * If set, this parameter is deprecated as of the given KCL version (e.g.,
 * "2.0"). The parser validates that this is a dotted integer version;
 * downstream code reparses it into a `VersionConstraint`.
 */
deprecated_since?: VersionConstraint | null, 
/**
 * If set, this parameter is removed as of the given KCL version (e.g.,
 * "3.0"). On that version or later, passing the parameter is an error,
 * exactly as if the function did not declare it, and the function body
 * sees the parameter's default value, or `none` if it has no default. A
 * pre-release version such as "3.0-preview" counts as the release it
 * precedes. May be combined with `deprecated` or `deprecated_since`.
 */
removed_since?: VersionConstraint | null, 
/**
 * The parameter's label or name.
 */
identifier: Node<Identifier>, 
/**
 * The type of the parameter.
 * This is optional if the user defines a type.
 */
param_type: Node<Type> | null, 
/**
 * Is the parameter optional?
 * If so, what is its default value?
 * If this is None, then the parameter is required.
 * Defaults to None.
 */
default_value?: DefaultParamVal | null, 
/**
 * Functions may declare at most one parameter without label, prefixed by '@', and it must be the first parameter.
 */
labeled?: boolean, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
