// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { ApiObjectId } from "./FrontendApi";
import type { PlaneKind } from "./PlaneKind";
import type { Point3d } from "./Point3d";

export type Plane = { 
/**
 * The id of the plane.
 */
id: string, 
/**
 * The artifact ID.
 */
artifactId: ArtifactId, 
/**
 * The scene object ID. If this is None, then the plane has not been
 * sent to the engine yet. It must be sent before it is used.
 */
objectId: ApiObjectId | null, 
/**
 * The kind of plane or custom.
 */
kind: PlaneKind, 
/**
 * Origin of the plane.
 */
origin: Point3d, 
/**
 * What should the plane's X axis be?
 */
xAxis: Point3d, 
/**
 * What should the plane's Y axis be?
 */
yAxis: Point3d, 
/**
 * What should the plane's Z axis be?
 */
zAxis: Point3d, };
