// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultTrue } from "./DefaultTrue";
import type { UnitLength } from "./ModelingCmd";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Project specific settings that affect the behavior while modeling.
 */
export type ProjectModelingSettings = { 
/**
 * The default unit to use in modeling dimensions.
 */
base_unit?: UnitLength | null, 
/**
 * Highlight edges of 3D objects?
 */
highlight_edges?: DefaultTrue, 
/**
 * Whether or not Screen Space Ambient Occlusion (SSAO) is enabled.
 */
enable_ssao?: DefaultTrue, 
/**
 * When enabled, the grid will use a fixed size based on your selected units rather than automatically scaling with zoom level.
 * If true, the grid cells will be fixed-size, where the width is your default length unit.
 * If false, the grid will get larger as you zoom out, and smaller as you zoom in.
 */
fixed_size_grid?: boolean | null, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
