// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedView } from "./NamedView";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Project specific application settings.
 */
export type ProjectAppSettings = { 
/**
 * When the user is idle, and this is true, the stream will be torn down.
 */
stream_idle_mode?: boolean, 
/**
 * Zookeeper reasoning mode. Uses the app default if not set.
 */
zookeeper_mode?: string | null, 
/**
 * Settings that affect the behavior of the command bar.
 */
named_views?: { [key in string]: NamedView }, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
