// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Runtime representation for feature flags that can be set by the TS app.
 *
 * TS currently provides a two-state feature answer: `true` means the feature is
 * on, while `false` covers both explicit off/default behavior and a missing
 * feature entry. Rust keeps a third state so code that was not initialized
 * through the TS/wasm path can still fall back to Rust-side defaults, such as
 * env-based configuration.
 */
export type RuntimeFlag = "Unset" | "On" | "Off";
