// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Segment, UnsolvedSegment } from "./Geometry";

export type SegmentRepr = { "Unsolved": { segment: UnsolvedSegment, } } | { "Solved": { segment: Segment, } };
