// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppSettings } from "./AppSettings";
import type { ModelingSettings } from "./ModelingSettings";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * High level settings.
 */
export type Settings = { 
/**
 * The settings for the Design Studio.
 */
app?: AppSettings | null, 
/**
 * Settings that affect the behavior while modeling.
 */
modeling?: ModelingSettings | null, } & ({ [key in string]: number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null });
