// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from "./ArtifactId";
import type { BasePathView } from "./BasePathView";
import type { UnitLength } from "./ModelingCmd";
import type { PathView } from "./PathView";
import type { ProfileClosedView } from "./ProfileClosedView";
import type { SketchSurfaceView } from "./SketchSurfaceView";
import type { TagIdentifierView } from "./TagIdentifierView";

export type SketchView = { type: "Sketch", id: string, originalId: string, paths: Array<PathView>, innerPaths?: Array<PathView>, on: SketchSurfaceView, start: BasePathView, tags?: { [key in string]: TagIdentifierView }, artifactId: ArtifactId, units: UnitLength, isClosed: ProfileClosedView, };
