// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SketchView } from "./SketchView";

export type SolidCreatorView = { "creatorType": "sketch" } & SketchView | { "creatorType": "face", face_id: string, solid_id: string, sketch: SketchView, } | { "creatorType": "edge", edge_id: string, body_id: string, } | { "creatorType": "procedural" };
