// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The first two items are the start and end points (byte offsets from the start of the file).
 * The third item is whether the source range belongs to the 'main' file, i.e., the file currently
 * being rendered/displayed in the editor.
 */
export type SourceRange = [number, number, number];
