// This file was generated by `cargo test -p kcl-lib export_bindings`.
// Do not edit this file by hand.

export default {
  "CCW": {
    "name": "CCW",
    "preferredName": "CCW",
    "qualName": "std::CCW",
    "moduleName": "std",
    "ty": "string",
    "value": {
      "source": "\"ccw\""
    },
    "summary": "Counterclockwise circular direction, currently used by `region()`.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "CW": {
    "name": "CW",
    "preferredName": "CW",
    "qualName": "std::CW",
    "moduleName": "std",
    "ty": "string",
    "value": {
      "source": "\"cw\""
    },
    "summary": "Clockwise circular direction, currently used by `region()`.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "E": {
    "name": "E",
    "preferredName": "E",
    "qualName": "std::math::E",
    "moduleName": "math",
    "ty": "number",
    "value": {
      "source": "2.71828182845904523536028747135266250_"
    },
    "summary": "The value of Euler’s number `e`.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "END": {
    "name": "END",
    "preferredName": "END",
    "qualName": "std::END",
    "moduleName": "std",
    "ty": "TaggedFace",
    "value": {
      "source": "'end'"
    },
    "summary": "Identifies the ending face of an extrusion. I.e., the new face created by an extrusion.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "MERGE": {
    "name": "MERGE",
    "preferredName": "MERGE",
    "qualName": "std::MERGE",
    "moduleName": "std",
    "ty": "string",
    "value": {
      "source": "\"merge\""
    },
    "summary": "Specifies that the extrusion will be pulled into or pushed out of the existing object, modifying it without creating a new object.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "NEW": {
    "name": "NEW",
    "preferredName": "NEW",
    "qualName": "std::NEW",
    "moduleName": "std",
    "ty": "string",
    "value": {
      "source": "\"new\""
    },
    "summary": "Specifies that a new object is created during extrusion.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "PI": {
    "name": "PI",
    "preferredName": "PI",
    "qualName": "std::math::PI",
    "moduleName": "math",
    "ty": "number(_?)",
    "value": {
      "source": "3.14159265358979323846264338327950288_?"
    },
    "summary": "The value of `pi`, Archimedes’ constant (π).",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "SOLID": {
    "name": "SOLID",
    "preferredName": "SOLID",
    "qualName": "std::SOLID",
    "moduleName": "std",
    "ty": "string",
    "value": {
      "source": "\"solid\""
    },
    "summary": "When bodies are solid, they have a top and bottom, and enclose all space between them.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "START": {
    "name": "START",
    "preferredName": "START",
    "qualName": "std::START",
    "moduleName": "std",
    "ty": "TaggedFace",
    "value": {
      "source": "'start'"
    },
    "summary": "Identifies the starting face of an extrusion. I.e., the face which is extruded.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "SURFACE": {
    "name": "SURFACE",
    "preferredName": "SURFACE",
    "qualName": "std::SURFACE",
    "moduleName": "std",
    "ty": "string",
    "value": {
      "source": "\"surface\""
    },
    "summary": "When bodies are surfaces, they have zero thickness. They are perfectly flat and do not enclose any space.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "TAU": {
    "name": "TAU",
    "preferredName": "TAU",
    "qualName": "std::math::TAU",
    "moduleName": "math",
    "ty": "number",
    "value": {
      "source": "6.28318530717958647692528676655900577_"
    },
    "summary": "The value of `tau`, the full circle constant (τ). Equal to 2π.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "X": {
    "name": "X",
    "preferredName": "X",
    "qualName": "std::X",
    "moduleName": "std",
    "ty": "Axis3d",
    "summary": "The X-axis (can be used in both 2d and 3d contexts).",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "XY": {
    "name": "XY",
    "preferredName": "XY",
    "qualName": "std::XY",
    "moduleName": "std",
    "ty": "Plane",
    "summary": "An abstract 3d plane aligned with the X and Y axes. Its normal is the positive Z axis.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "XZ": {
    "name": "XZ",
    "preferredName": "XZ",
    "qualName": "std::XZ",
    "moduleName": "std",
    "ty": "Plane",
    "summary": "An abstract 3d plane aligned with the X and Z axes. Its normal is the negative Y axis.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "Y": {
    "name": "Y",
    "preferredName": "Y",
    "qualName": "std::Y",
    "moduleName": "std",
    "ty": "Axis3d",
    "summary": "The Y-axis (can be used in both 2d and 3d contexts).",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "YZ": {
    "name": "YZ",
    "preferredName": "YZ",
    "qualName": "std::YZ",
    "moduleName": "std",
    "ty": "Plane",
    "summary": "An abstract 3d plane aligned with the Y and Z axes. Its normal is the positive X axis.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "Z": {
    "name": "Z",
    "preferredName": "Z",
    "qualName": "std::Z",
    "moduleName": "std",
    "ty": "Axis3d",
    "summary": "The 3D Z-axis.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "solver::ORIGIN": {
    "name": "ORIGIN",
    "preferredName": "solver::ORIGIN",
    "qualName": "std::solver::ORIGIN",
    "moduleName": "solver",
    "ty": "Point2d",
    "summary": "The origin point in a sketch.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "sweep::SKETCH_PLANE": {
    "name": "SKETCH_PLANE",
    "preferredName": "sweep::SKETCH_PLANE",
    "qualName": "std::sweep::SKETCH_PLANE",
    "moduleName": "sweep",
    "ty": "string",
    "value": {
      "source": "'sketchPlane'"
    },
    "summary": "Local/relative to a position centered within the plane being sketched on",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "sweep::TRAJECTORY": {
    "name": "TRAJECTORY",
    "preferredName": "sweep::TRAJECTORY",
    "qualName": "std::sweep::TRAJECTORY",
    "moduleName": "sweep",
    "ty": "string",
    "value": {
      "source": "'trajectoryCurve'"
    },
    "summary": "Local/relative to the trajectory curve",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "turns::HALF_TURN": {
    "name": "HALF_TURN",
    "preferredName": "turns::HALF_TURN",
    "qualName": "std::turns::HALF_TURN",
    "moduleName": "turns",
    "ty": "number(deg)",
    "value": {
      "source": "180deg"
    },
    "summary": "A half turn, 180 degrees or π radians.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "turns::QUARTER_TURN": {
    "name": "QUARTER_TURN",
    "preferredName": "turns::QUARTER_TURN",
    "qualName": "std::turns::QUARTER_TURN",
    "moduleName": "turns",
    "ty": "number(deg)",
    "value": {
      "source": "90deg"
    },
    "summary": "A quarter turn, 90 degrees or π/2 radians.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "turns::THREE_QUARTER_TURN": {
    "name": "THREE_QUARTER_TURN",
    "preferredName": "turns::THREE_QUARTER_TURN",
    "qualName": "std::turns::THREE_QUARTER_TURN",
    "moduleName": "turns",
    "ty": "number(deg)",
    "value": {
      "source": "270deg"
    },
    "summary": "Three quarters of a turn, 270 degrees or 1.5*π radians.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  },
  "turns::ZERO": {
    "name": "ZERO",
    "preferredName": "turns::ZERO",
    "qualName": "std::turns::ZERO",
    "moduleName": "turns",
    "ty": "number(Angle)",
    "value": {
      "source": "0"
    },
    "summary": "No turn, zero degrees/radians.",
    "deprecated": false,
    "deprecatedSince": null,
    "experimental": false,
    "docHidden": false
  }
} as const
