// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleId } from "./ModuleId";

/**
 * The presentational portion of a tag declaration, including its source location.
 */
export type TagDeclaratorView = { commentStart: number, end: number, moduleId: ModuleId, start: number, type: "TagDeclarator", value: string, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
