// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtrudeSurface } from "./ExtrudeSurface";
import type { GeometryWithImportedGeometry } from "./GeometryWithImportedGeometry";
import type { Path } from "./Path";

/**
 * Engine information for a tag.
 */
export type TagEngineInfo = { "type": "TagEngineInfo", 
/**
 * The id of the tagged object.
 */
id: string, 
/**
 * The geometry the tag is on.
 */
geometry: GeometryWithImportedGeometry, 
/**
 * The path the tag is on.
 */
path: Path | null, 
/**
 * The surface information for the tag.
 */
surface: ExtrudeSurface | null, };
