// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagIdentifier } from "./TagIdentifier";

/**
 * Tag or UUID for use in an unresolved edge specifier (resolved to face UUIDs in blend).
 */
export type TagOrUuid = string | TagIdentifier;
