// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from "./Identifier";
import type { ItemVisibility } from "./ItemVisibility";
import type { Node } from "./Node";
import type { TypeDeclarationDefinition } from "./TypeDeclarationDefinition";

export type TypeDeclaration = { "type": "TypeDeclaration", name: Node<Identifier>, args: Array<Node<Identifier>> | null, visibility?: ItemVisibility, definition: TypeDeclarationDefinition, digest?: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number], };
