// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitAngle, UnitLength } from "./ModelingCmd";

export type UnitType = { "type": "Count" } | { "type": "Length" } & UnitLength | { "type": "GenericLength" } | { "type": "Angle" } & UnitAngle | { "type": "GenericAngle" } | { "type": "Dimensional", length_unit: UnitLength, length_exponent: number, angle_unit: UnitAngle, angle_exponent: number, };
