// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TagOrUuid } from "./TagOrUuid";

/**
 * Edge specifier payload (sideFaces, endFaces, index) as passed from KCL. Stored in BoundedEdge and resolved to `kcmc::shared::EdgeSpecifier` in blend().
 */
export type UnresolvedEdgeSpecifier = { sideFaces?: Array<TagOrUuid>, endFaces?: Array<TagOrUuid>, index?: number | null, };
