// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether the objects of a named view start visible or hidden.
 *
 * Rust mirror of the KCL enum `std::view::Visibility`. Serialized variant
 * names match the KCL spellings exactly.
 */
export type Visibility = "Show" | "Hide";
