center = [0,0]
radius = 40
height = 3

body = startSketchOn(XY)
  |> startProfile(at = [center[0]+radius, center[1]])
  |> arc(angleEnd = 360deg, angleStart = 0deg, radius = radius)
  |> close()
  |> extrude(length = height)
