wall_thickness = 0.125
back_walls_width = 2
front_walls_width = 2.5
height = 5.5
filletRadius = 0.050
back_length = 7
exit_height = 1
front_length = 6
Fx = 0.5
Fy = 0.5

sketch001 = startSketchOn(-YZ)
  |> startProfile(at = [back_walls_width / 2, 0])
  |> xLine(length = wall_thickness / 2)
  |> angledLine(angle = 45deg, endAbsoluteX = back_walls_width, tag = $seg01)
  |> yLine(endAbsolute = height)
  |> xLine(length = -wall_thickness)
  |> yLine(endAbsolute = segEndY(seg01))
  |> angledLine(angle = 45deg, endAbsoluteX = back_walls_width / 2 + wall_thickness / 2)
  |> xLine(length = -wall_thickness)
  |> angledLine(angle = 180deg - 45, endAbsoluteX = wall_thickness)
  |> yLine(endAbsolute = height)
  |> xLine(endAbsolute = 0)
  |> yLine(endAbsolute = segEndY(seg01))
  |> angledLine(angle = 180deg - 45, endAbsoluteY = 0)
  |> close()
part001 = revolve({
  angle: 90,
  axis: {
    custom: {
      axis: [1.0, 0.0],
      origin: [0.0, height + .0000001]
    }
  }
}, sketch001)

sketch002 = startSketchOn(-YZ)
  |> startProfile(at = [back_walls_width / 2, 0])
  |> xLine(length = wall_thickness / 2)
  |> angledLine(angle = 45deg, endAbsoluteX = back_walls_width, tag = $seg02)
  |> yLine(endAbsolute = height)
  |> xLine(length = -wall_thickness)
  |> yLine(endAbsolute = segEndY(seg01))
  |> angledLine(angle = 45deg, endAbsoluteX = back_walls_width / 2 + wall_thickness / 2)
  |> xLine(length = -wall_thickness)
  |> angledLine(angle = 180deg - 45, endAbsoluteX = wall_thickness)
  |> yLine(endAbsolute = height)
  |> xLine(endAbsolute = 0)
  |> yLine(endAbsolute = segEndY(seg02))
  |> angledLine(angle = 180deg - 45, endAbsoluteY = 0)
  |> close()
  |> extrude(length = back_length - height)