// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObjectId } from './ApiObjectId'
import type { SegmentCtor } from './SegmentCtor'

export type ApiLine = {
  start: ApiObjectId
  end: ApiObjectId
  ctor: SegmentCtor
  ctor_applicable: boolean
}
