// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiArc } from './ApiArc'
import type { ApiCircle } from './ApiCircle'
import type { ApiLine } from './ApiLine'
import type { ApiPoint } from './ApiPoint'

export type ApiSegment =
  | { Point: ApiPoint }
  | { Line: ApiLine }
  | { Arc: ApiArc }
  | { Circle: ApiCircle }
