// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObjectId } from './ApiObjectId'
import type { SketchArgs } from './SketchArgs'

export type ApiSketch = {
  args: SketchArgs
  segments: Array<ApiObjectId>
  constraints: Array<ApiObjectId>
}
