// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppColor } from './AppColor'
import type { AppTheme } from './AppTheme'

/**
 * The settings for the theme of the app.
 */
export type AppearanceSettings = {
  /**
   * The overall theme of the app.
   */
  theme?: AppTheme
  /**
   * The hue of the primary theme color for the app.
   */
  color?: AppColor
}
