// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSettings } from './AppearanceSettings'
import type { OnboardingStatus } from './OnboardingStatus'

/**
 * Application wide settings.
 */
export type AppSettings = {
  /**
   * The settings for the appearance of the app.
   */
  appearance?: AppearanceSettings
  /**
   * The onboarding status of the app.
   */
  onboarding_status?: OnboardingStatus
  /**
   * Permanently dismiss the banner warning to download the desktop app.
   * This setting only applies to the web app. And is temporary until we have Linux support.
   */
  dismiss_web_banner?: boolean
  /**
   * When the user is idle, teardown the stream after some time.
   */
  stream_idle_mode?: number | null
  /**
   * Allow orbiting in sketch mode.
   */
  allow_orbit_in_sketch_mode?: boolean
  /**
   * Whether to show the debug panel, which lets you see various states
   * of the app to aid in development.
   */
  show_debug_panel?: boolean
}
