// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The overall appearance of the app.
 */
export type AppTheme = 'light' | 'dark' | 'system'
