// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Annotation } from './Annotation'
import type { BodyItem } from './BodyItem'
import type { Node } from './Node'
import type { NonCodeMeta } from './NonCodeMeta'

export type Block = {
  type: 'Block'
  items: Array<BodyItem>
  non_code_meta?: NonCodeMeta
  inner_attrs?: Array<Node<Annotation>>
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
