// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from './Expr'
import type { LabeledArg } from './LabeledArg'
import type { Name } from './Name'
import type { Node } from './Node'
import type { NonCodeMeta } from './NonCodeMeta'

export type CallExpressionKw = {
  type: 'CallExpressionKw'
  callee: Node<Name>
  unlabeled: Expr | null
  arguments: Array<LabeledArg>
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
  nonCodeMeta?: NonCodeMeta
}
