// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The types of camera projection for the 3D view.
 */
export type CameraProjectionType = 'perspective' | 'orthographic'
