// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Choices = {
  text: string
  index: number
  finishReason: string | null
  logprobs: string | null
}
