// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObjectId } from './ApiObjectId'

export type Coincident = { points: Array<ApiObjectId> }
