// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Settings } from './Settings'

/**
 * User specific settings for the app.
 * These live in `user.toml` in the app's configuration directory.
 * Updating the settings in the app will update this file automatically.
 * Do not edit this file manually, as it may be overwritten by the app.
 * Manual edits can cause corruption of the settings file.
 */
export type Configuration = {
  /**
   * The settings for the Design Studio.
   */
  settings?: Settings
}
