// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopilotCyclingCompletion } from './CopilotCyclingCompletion'
import type { CopilotLspCompletionParams } from './CopilotLspCompletionParams'

export type CopilotCompletionTelemetry = {
  completion: CopilotCyclingCompletion
  params: CopilotLspCompletionParams
}
