// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorConfiguration } from './EditorConfiguration'
import type { EditorInfo } from './EditorInfo'

export type CopilotEditorInfo = {
  editorConfiguration: EditorConfiguration
  editorInfo: EditorInfo
  editorPluginInfo: EditorInfo
}
