// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopilotPosition } from './CopilotPosition'

export type CopilotDocParams = {
  indentSize: number
  insertSpaces: boolean
  languageId: string
  path: string
  position: CopilotPosition
  relativePath: string
  source: string
  tabSize: number
  uri: string
}
