// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopilotPosition } from './CopilotPosition'
import type { CopilotRange } from './CopilotRange'

export type CopilotCyclingCompletion = {
  uuid: string
  displayText: string
  text: string
  range: CopilotRange
  position: CopilotPosition
}
