// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KclNone } from './KclNone'
import type { Literal } from './Literal'
import type { Node } from './Node'

/**
 * Default value for a parameter of a KCL function.
 */
export type DefaultParamVal =
  | ({ type: 'KclNone' } & KclNone)
  | ({ type: 'Literal' } & Node<Literal>)
