// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The executor settings.
 */
export type ExecutorSettings = {
  /**
   * Highlight edges of 3D objects?
   */
  highlight_edges: boolean
  /**
   * Whether or not Screen Space Ambient Occlusion (SSAO) is enabled.
   */
  enable_ssao: boolean
  /**
   * Show grid?
   */
  show_grid: boolean
  /**
   * Should engine store this for replay?
   * If so, under what name?
   */
  replay: string | null
  /**
   * The directory of the current project.  This is used for resolving import
   * paths.  If None is given, the current working directory is used.
   */
  project_directory: string | null
  /**
   * This is the path to the current file being executed.
   * We use this for preventing cyclic imports.
   */
  current_file: string | null
  /**
   * Whether or not to automatically scale the grid when user zooms.
   */
  fixed_size_grid: boolean
}
