// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChamferSurface } from './ChamferSurface'
import type { ExtrudeArc } from './ExtrudeArc'
import type { ExtrudePlane } from './ExtrudePlane'
import type { FilletSurface } from './FilletSurface'

/**
 * An extrude surface.
 */
export type ExtrudeSurface =
  | ({ type: 'extrudePlane' } & ExtrudePlane)
  | ({ type: 'extrudeArc' } & ExtrudeArc)
  | ({ type: 'chamfer' } & ChamferSurface)
  | ({ type: 'fillet' } & FilletSurface)
