// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Abstract lint problem type.
 */
export type Finding = {
  /**
   * Unique identifier for this particular issue.
   */
  code: string
  /**
   * Short one-line description of this issue.
   */
  title: string
  /**
   * Long human-readable description of this issue.
   */
  description: string
  /**
   * Is this discovered issue experimental?
   */
  experimental: boolean
}
