// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Format options.
 */
export type FormatOptions = {
  /**
   * Size of a tab in spaces.
   */
  tabSize: number
  /**
   * Prefer tabs over spaces.
   */
  useTabs: boolean
  /**
   * How to handle the final newline in the file.
   * If true, ensure file ends with a newline.
   * If false, ensure file does not end with a newline.
   */
  insertFinalNewline: boolean
}
