// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRange } from './SourceRange'

/**
 * Geometry metadata.
 */
export type GeoMeta = {
  /**
   * The id of the geometry.
   */
  id: string
  /**
   * The source range.
   */
  sourceRange: SourceRange
}
