// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportedGeometry } from './ImportedGeometry'
import type { Sketch } from './Sketch'
import type { Solid } from './Solid'

/**
 * A geometry including an imported geometry.
 */
export type GeometryWithImportedGeometry =
  | ({ type: 'Sketch' } & Sketch)
  | ({ type: 'Solid' } & Solid)
  | ({ type: 'ImportedGeometry' } & ImportedGeometry)
