// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sketch } from './Sketch'
import type { Solid } from './Solid'

/**
 * A geometry.
 */
export type Geometry =
  | ({ type: 'Sketch' } & Sketch)
  | ({ type: 'Solid' } & Solid)
