// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from './ArtifactId'
import type { UnitLength } from './ModelingCmd'

/**
 * A helix.
 */
export type Helix = {
  /**
   * The id of the helix.
   */
  value: string
  /**
   * The artifact ID.
   */
  artifactId: ArtifactId
  /**
   * Number of revolutions.
   */
  revolutions: number
  /**
   * Start angle (in degrees).
   */
  angleStart: number
  /**
   * Is the helix rotation counter clockwise?
   */
  ccw: boolean
  /**
   * The cylinder the helix was created on.
   */
  cylinderId: string | null
  units: UnitLength
}
