// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiFile } from './ApiFile'
import type { Error } from './Error'
import type { SceneGraphDelta } from './SceneGraphDelta'

export type IgnoreMe = { a: Error; b: SceneGraphDelta; c: ApiFile }
