// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from './Identifier'
import type { ImportItem } from './ImportItem'
import type { Node } from './Node'

export type ImportSelector =
  | { type: 'List'; items: Array<Node<ImportItem>> }
  | ({ type: 'Glob' } & Node<null>)
  | { type: 'None'; alias: Node<Identifier> | null }
