// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImportPath =
  | { type: 'Kcl'; filename: string }
  | { type: 'Foreign'; path: string }
  | { type: 'Std'; path: Array<string> }
