// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportPath } from './ImportPath'
import type { ImportSelector } from './ImportSelector'
import type { ItemVisibility } from './ItemVisibility'

export type ImportStatement = {
  type: 'ImportStatement'
  selector: ImportSelector
  path: ImportPath
  visibility?: ItemVisibility
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
