// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Data for an imported geometry.
 */
export type ImportedGeometry = {
  /**
   * The ID of the imported geometry.
   */
  id: string
  /**
   * The original file paths.
   */
  value: Array<string>
}
