// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactCommand, ArtifactGraph } from './Artifact'
import type { CompilationError } from './CompilationError'
import type { DefaultPlanes } from './DefaultPlanes'
import type { KclError } from './KclError'
import type { KclValue } from './KclValue'
import type { ModuleId } from './ModuleId'
import type { ModulePath } from './ModulePath'
import type { ModuleSource } from './ModuleSource'
import type { Operation } from './Operation'

export type KclErrorWithOutputs = {
  error: KclError
  nonFatal: Array<CompilationError>
  /**
   * Variables in the top-level of the root module. Note that functions will
   * have an invalid env ref.
   */
  variables: { [key in string]?: KclValue }
  operations: Array<Operation>
  artifactCommands: Array<ArtifactCommand>
  artifactGraph: ArtifactGraph
  filenames: { [key in ModuleId]?: ModulePath }
  sourceFiles: { [key in ModuleId]?: ModuleSource }
  defaultPlanes: DefaultPlanes | null
}
