// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BacktraceItem } from './BacktraceItem'
import type { SourceRange } from './SourceRange'

export type KclErrorDetails = {
  sourceRanges: Array<SourceRange>
  backtrace: Array<BacktraceItem>
  msg: string
}
