// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumericSuffix } from './NumericSuffix'

export type LiteralValue =
  | { value: number; suffix: NumericSuffix }
  | string
  | boolean
