// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceRange } from './SourceRange'

/**
 * Metadata.
 */
export type Metadata = {
  /**
   * The source range.
   */
  sourceRange: SourceRange
}
