// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModulePath =
  | { type: 'Main' }
  | { type: 'Local'; value: string }
  | { type: 'Std'; value: string }
