// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The types of controls for how to navigate the 3D view.
 */
export type MouseControlType =
  | 'zoo'
  | 'onshape'
  | 'trackpad_friendly'
  | 'solidworks'
  | 'nx'
  | 'creo'
  | 'autocad'
