// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NamedView = {
  /**
   * User defined name to identify the named view. A label.
   */
  name: string
  /**
   * Engine camera eye off set
   */
  eye_offset: number
  /**
   * Engine camera vertical FOV
   */
  fov_y: number
  is_ortho: boolean
  /**
   * Engine camera is orthographic camera scaling enabled
   */
  ortho_scale_enabled: boolean
  /**
   * Engine camera orthographic scaling factor
   */
  ortho_scale_factor: number
  /**
   * Engine camera position that the camera pivots around
   */
  pivot_position: [number, number, number]
  /**
   * Engine camera orientation in relation to the pivot position
   */
  pivot_rotation: [number, number, number, number]
  /**
   * Engine camera world coordinate system orientation
   */
  world_coord_system: string
  /**
   * Version number of the view point if the engine camera API changes
   */
  version: number
}
