// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from './Identifier'
import type { Node } from './Node'

/**
 * A qualified name, e.g., `foo`, `bar::foo`, or `::bar::foo`.
 */
export type Name = {
  type: 'Name'
  name: Node<Identifier>
  path: Array<Node<Identifier>>
  abs_path: boolean
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
