// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiObjectId } from './ApiObjectId'
import type { ObjectKind } from './ObjectKind'
import type { SourceRef } from './SourceRef'

export type Object = {
  id: ApiObjectId
  kind: ObjectKind
  label: string
  comments: string
  artifact_id: number
  source: SourceRef
}
