// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectAppSettings } from './ProjectAppSettings'
import type { ProjectCommandBarSettings } from './ProjectCommandBarSettings'
import type { ProjectMetaSettings } from './ProjectMetaSettings'
import type { ProjectModelingSettings } from './ProjectModelingSettings'
import type { ProjectTextEditorSettings } from './ProjectTextEditorSettings'

/**
 * High level project settings.
 */
export type PerProjectSettings = {
  /**
   * Information about the project itself.
   * Choices about how settings are merged have prevent me (lee) from easily
   * moving this out of the settings structure.
   */
  meta: ProjectMetaSettings
  /**
   * The settings for the Design Studio.
   */
  app: ProjectAppSettings
  /**
   * Settings that affect the behavior while modeling.
   */
  modeling: ProjectModelingSettings
  /**
   * Settings that affect the behavior of the KCL text editor.
   */
  text_editor: ProjectTextEditorSettings
  /**
   * Settings that affect the behavior of the command bar.
   */
  command_bar: ProjectCommandBarSettings
}
