// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from './ArtifactId'
import type { PlaneType } from './PlaneType'
import type { Point3d } from './Point3d'

export type Plane = {
  /**
   * The id of the plane.
   */
  id: string
  /**
   * The artifact ID.
   */
  artifactId: ArtifactId
  value: PlaneType
  /**
   * Origin of the plane.
   */
  origin: Point3d
  /**
   * What should the plane's X axis be?
   */
  xAxis: Point3d
  /**
   * What should the plane's Y axis be?
   */
  yAxis: Point3d
  /**
   * What should the plane's Z axis be?
   */
  zAxis: Point3d
}
