// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Point3d } from './Point3d'

export type PlaneInfo = {
  /**
   * Origin of the plane.
   */
  origin: Point3d
  /**
   * What should the plane's X axis be?
   */
  xAxis: Point3d
  /**
   * What should the plane's Y axis be?
   */
  yAxis: Point3d
  /**
   * What should the plane's Z axis be?
   */
  zAxis: Point3d
}
