// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectNameTemplate } from './ProjectNameTemplate'

/**
 * Settings that affect the behavior of project management.
 */
export type ProjectSettings = {
  /**
   * The directory to save and load projects from.
   */
  directory?: string
  /**
   * The default project name to use when creating a new project.
   */
  default_project_name?: ProjectNameTemplate
}
