// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedView } from './NamedView'
import type { OnboardingStatus } from './OnboardingStatus'
import type { ProjectAppearanceSettings } from './ProjectAppearanceSettings'

/**
 * Project specific application settings.
 */
export type ProjectAppSettings = {
  /**
   * The settings for the appearance of the app.
   */
  appearance?: ProjectAppearanceSettings
  /**
   * The onboarding status of the app.
   */
  onboarding_status?: OnboardingStatus
  /**
   * Permanently dismiss the banner warning to download the desktop app.
   * This setting only applies to the web app. And is temporary until we have Linux support.
   */
  dismiss_web_banner?: boolean
  /**
   * When the user is idle, and this is true, the stream will be torn down.
   */
  stream_idle_mode?: boolean
  /**
   * When the user is idle, and this is true, the stream will be torn down.
   */
  allow_orbit_in_sketch_mode?: boolean
  /**
   * Whether to show the debug panel, which lets you see various states
   * of the app to aid in development.
   */
  show_debug_panel?: boolean | null
  /**
   * Settings that affect the behavior of the command bar.
   */
  named_views?: { [key in string]?: NamedView }
}
