// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Same as CommandBarSettings but applies to a per-project basis.
 */
export type ProjectCommandBarSettings = {
  /**
   * Whether to include settings in the command bar.
   */
  include_settings?: boolean | null
}
