// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sketch } from './Sketch'
import type { SketchSurface } from './SketchSurface'

/**
 * A sketch surface or a sketch.
 */
export type SketchOrSurface = SketchSurface | Sketch
