// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block } from './Block'
import type { LabeledArg } from './LabeledArg'
import type { Node } from './Node'
import type { NonCodeMeta } from './NonCodeMeta'

export type SketchBlock = {
  type: 'SketchBlock'
  arguments: Array<LabeledArg>
  body: Node<Block>
  non_code_meta?: NonCodeMeta
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
