// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Face } from './Face'
import type { Plane } from './Plane'

/**
 * A sketch type.
 */
export type SketchSurface =
  | ({ type: 'plane' } & Plane)
  | ({ type: 'face' } & Face)
