// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArtifactId } from './ArtifactId'
import type { EdgeCut } from './EdgeCut'
import type { ExtrudeSurface } from './ExtrudeSurface'
import type { UnitLength } from './ModelingCmd'
import type { Sketch } from './Sketch'

export type Solid = {
  type: 'Solid'
  /**
   * The id of the solid.
   */
  id: string
  /**
   * The artifact ID of the solid.  Unlike `id`, this doesn't change.
   */
  artifactId: ArtifactId
  /**
   * The extrude surfaces.
   */
  value: Array<ExtrudeSurface>
  /**
   * The sketch.
   */
  sketch: Sketch
  /**
   * The id of the extrusion start cap
   */
  startCapId: string | null
  /**
   * The id of the extrusion end cap
   */
  endCapId: string | null
  /**
   * Chamfers or fillets on this solid.
   */
  edgeCuts?: Array<EdgeCut>
  /**
   * The units of the solid.
   */
  units: UnitLength
  /**
   * Is this a sectional solid?
   */
  sectional: boolean
}
