// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Helix } from './Helix'
import type { Sketch } from './Sketch'

/**
 * A path to sweep along.
 */
export type SweepPath = Sketch | Helix
