// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtrudeSurface } from './ExtrudeSurface'
import type { Path } from './Path'

/**
 * Engine information for a tag.
 */
export type TagEngineInfo = {
  type: 'TagEngineInfo'
  /**
   * The id of the tagged object.
   */
  id: string
  /**
   * The sketch the tag is on.
   */
  sketch: string
  /**
   * The path the tag is on.
   */
  path: Path | null
  /**
   * The surface information for the tag.
   */
  surface: ExtrudeSurface | null
}
