// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TyF64 } from './TyF64'

/**
 * Data to draw a tangential arc.
 */
export type TangentialArcData = {
  /**
   * Radius of the arc.
   * Not to be confused with Raiders of the Lost Ark.
   */
  radius: TyF64
  /**
   * Offset of the arc, in degrees.
   */
  offset: TyF64
}
