// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DefaultTrue } from './DefaultTrue'

/**
 * Settings that affect the behavior of the KCL text editor.
 */
export type TextEditorSettings = {
  /**
   * Whether to wrap text in the editor or overflow with scroll.
   */
  text_wrapping?: DefaultTrue
  /**
   * Whether to make the cursor blink in the editor.
   */
  blinking_cursor?: DefaultTrue
}
