// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NumericType } from './NumericType'

export type TyF64 = { n: number; ty: NumericType }
