// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArrayLen } from './ArrayLen'
import type { Identifier } from './Identifier'
import type { Node } from './Node'
import type { PrimitiveType } from './PrimitiveType'

export type Type =
  | ({ type: 'Primitive' } & PrimitiveType)
  | { type: 'Array'; ty: Type; len: ArrayLen }
  | { type: 'Union'; tys: Array<Node<Type>> }
  | { type: 'Object'; properties: Array<[Node<Identifier>, Node<Type>]> }
