// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Identifier } from './Identifier'
import type { ItemVisibility } from './ItemVisibility'
import type { Node } from './Node'
import type { Type } from './Type'

export type TypeDeclaration = {
  type: 'TypeDeclaration'
  name: Node<Identifier>
  args: Array<Node<Identifier>> | null
  visibility?: ItemVisibility
  alias: Node<Type> | null
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
