// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinaryPart } from './BinaryPart'
import type { UnaryOperator } from './UnaryOperator'

export type UnaryExpression = {
  type: 'UnaryExpression'
  operator: UnaryOperator
  argument: BinaryPart
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
