// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitLength } from './ModelingCmd'
import type { TextDocumentIdentifier } from './TextDocumentIdentifier'

export type UpdateUnitsParams = {
  textDocument: TextDocumentIdentifier
  /**
   * The content of the text document.
   */
  text: string
  units: UnitLength
}
