// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Expr } from './Expr'
import type { Identifier } from './Identifier'
import type { Node } from './Node'

export type VariableDeclarator = {
  type: 'VariableDeclarator'
  /**
   * The identifier of the variable.
   */
  id: Node<Identifier>
  /**
   * The value of the variable.
   */
  init: Expr
  digest?: [
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
  ]
}
