// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The webrtc stats structure.
 */
export type WebrtcStats = {
  /**
   * The packets lost.
   */
  packets_lost?: number | null
  /**
   * The frames received.
   */
  frames_received?: number | null
  /**
   * The frame width.
   */
  frame_width?: number | null
  /**
   * The frame height.
   */
  frame_height?: number | null
  /**
   * The frame rate.
   */
  frame_rate?: number | null
  /**
   * The number of key frames decoded.
   */
  key_frames_decoded?: number | null
  /**
   * The number of frames dropped.
   */
  frames_dropped?: number | null
  /**
   * The pause count.
   */
  pause_count?: number | null
  /**
   * The total pauses duration.
   */
  total_pauses_duration?: number | null
  /**
   * The freeze count.
   */
  freeze_count?: number | null
  /**
   * The total freezes duration.
   */
  total_freezes_duration?: number | null
  /**
   * The pli count.
   */
  pli_count?: number | null
  /**
   * Packet jitter for this synchronizing source, measured in seconds.
   */
  jitter?: number | null
}
