import type { Layout } from '@src/lib/layout/types'

export const testLayout: Layout = {
  id: crypto.randomUUID(),
  label: 'root',
  type: 'splits',
  orientation: 'block',
  sizes: [30, 20, 40],
  children: [
    {
      id: crypto.randomUUID(),
      label: 'split',
      type: 'splits',
      sizes: [50, 25, 25],
      orientation: 'inline',
      children: [
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: 'simple',
          areaType: 'modeling',
        },
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: 'simple',
          areaType: 'variables',
        },
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: 'simple',
          areaType: 'modeling',
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      label: 'middle-split',
      type: 'splits',
      sizes: [75, 25],
      orientation: 'inline',
      children: [
        {
          id: crypto.randomUUID(),
          label: 'right-toolbar',
          type: 'panes',
          side: 'inline-end',
          splitOrientation: 'block',
          activeIndices: [0, 2, 3],
          sizes: [20, 20, 60],
          paneIcons: ['sparkles', 'make-variable', 'glasses', 'revolve'],
          children: [
            {
              id: crypto.randomUUID(),
              label: crypto.randomUUID(),
              type: 'simple',
              areaType: 'ttc',
            },
            {
              id: crypto.randomUUID(),
              label: crypto.randomUUID(),
              type: 'simple',
              areaType: 'variables',
            },
            {
              id: crypto.randomUUID(),
              label: 'right-toolbar',
              type: 'panes',
              side: 'block-start',
              splitOrientation: 'inline',
              activeIndices: [0, 2, 3],
              sizes: [20, 20, 60],
              paneIcons: ['sparkles', 'make-variable', 'code', 'revolve'],
              children: [
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: 'simple',
                  areaType: 'ttc',
                },
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: 'simple',
                  areaType: 'variables',
                },
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: 'simple',
                  areaType: 'codeEditor',
                },
                {
                  id: crypto.randomUUID(),
                  label: crypto.randomUUID(),
                  type: 'simple',
                  areaType: 'featureTree',
                },
              ],
            },
            {
              id: crypto.randomUUID(),
              label: crypto.randomUUID(),
              type: 'simple',
              areaType: 'featureTree',
            },
          ],
        },
        {
          id: crypto.randomUUID(),
          label: 'modeling-scene',
          type: 'simple',
          areaType: 'variables',
        },
      ],
    },
    {
      id: crypto.randomUUID(),
      label: 'right-toolbar',
      type: 'panes',
      side: 'block-start',
      splitOrientation: 'inline',
      activeIndices: [0, 2, 3],
      sizes: [20, 20, 60],
      paneIcons: ['sparkles', 'make-variable', 'code', 'revolve'],
      children: [
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: 'simple',
          areaType: 'ttc',
        },
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: 'simple',
          areaType: 'variables',
        },
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: 'simple',
          areaType: 'codeEditor',
        },
        {
          id: crypto.randomUUID(),
          label: crypto.randomUUID(),
          type: 'simple',
          areaType: 'featureTree',
        },
      ],
    },
  ],
}
