import { defineRegistryItem, provide } from '@kittycad/registry'
import { isDesktop } from '@src/lib/isDesktop'
import {
  type KeymapDocument,
  MODE_MODELING_KEYMAP_SCOPE,
  MODE_SKETCHING_KEYMAP_SCOPE,
  MODE_SKETCH_NO_FACE_KEYMAP_SCOPE,
  MODE_SKETCH_SOLVE_KEYMAP_SCOPE,
  keymapValueSpec,
} from '@src/registry/contracts/keymap'
import { TOOLBAR_COMMAND_IDS } from '@src/registry/extensions/commands/toolbarCommands'

const BASE_KEYMAP_SOURCE = 'Base'

function createExitSketchBindings({
  id,
  scope,
  command,
}: {
  id: string
  scope: string
  command: string
}): KeymapDocument['bindings'] {
  return [
    {
      id,
      title: 'Exit Sketch',
      scopes: [scope],
      keystrokes: ['shift+escape'],
      command,
    },
  ]
}

export const defaultKeymap: KeymapDocument = {
  source: BASE_KEYMAP_SOURCE,
  bindings: [
    {
      id: 'command-palette.open',
      title: 'Open command palette',
      keystrokes: ['mod+k'],
      command: 'zds.commandPalette.open',
    },
    {
      id: 'command-palette.close',
      title: 'Close command palette',
      scopes: ['cmd-palette-open'],
      keystrokes: ['mod+k'],
      command: 'zds.commandPalette.close',
    },
    {
      id: 'settings.open',
      title: 'Open settings',
      keystrokes: [isDesktop() ? 'mod+,' : 'mod+shift+,'],
      command: 'zds.settings.open',
    },
    {
      id: 'settings.project',
      title: 'Project settings',
      scopes: ['settings-open'],
      keystrokes: ['p'],
      command: 'zds.settings.tab',
      arguments: {
        tab: 'project',
      },
    },
    {
      id: 'settings.user',
      title: 'User settings',
      scopes: ['settings-open'],
      keystrokes: ['u'],
      command: 'zds.settings.tab',
      arguments: {
        tab: 'user',
      },
    },
    {
      id: 'view.top',
      title: 'Top view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '1'],
      command: 'standardViews:Top view',
    },
    {
      id: 'view.right',
      title: 'Right view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '2'],
      command: 'standardViews:Right view',
    },
    {
      id: 'view.front',
      title: 'Front view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '3'],
      command: 'standardViews:Front view',
    },
    {
      id: 'view.back',
      title: 'Back view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '4'],
      command: 'standardViews:Back view',
    },
    {
      id: 'view.bottom',
      title: 'Bottom view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '5'],
      command: 'standardViews:Bottom view',
    },
    {
      id: 'view.left',
      title: 'Left view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '6'],
      command: 'standardViews:Left view',
    },
    {
      id: 'view.zoom-to-fit',
      title: 'Zoom to fit',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', 'f'],
      command: 'standardViews:Zoom to fit',
    },
    {
      id: 'view.reset',
      title: 'Reset view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', 'r'],
      command: 'zds.view.reset',
    },
    {
      id: 'toolbar.modeling.sketch',
      title: 'Start or edit sketch',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['s'],
      command: TOOLBAR_COMMAND_IDS.modeling.sketch,
    },
    {
      id: 'toolbar.modeling.extrude',
      title: 'Extrude',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['e'],
      command: 'modeling:Extrude',
    },
    {
      id: 'toolbar.modeling.sweep',
      title: 'Sweep',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['w'],
      command: 'modeling:Sweep',
    },
    {
      id: 'toolbar.modeling.loft',
      title: 'Loft',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['l'],
      command: 'modeling:Loft',
    },
    {
      id: 'toolbar.modeling.revolve',
      title: 'Revolve',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['r'],
      command: 'modeling:Revolve',
    },
    {
      id: 'toolbar.modeling.fillet',
      title: 'Fillet',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['f'],
      command: 'modeling:Fillet',
    },
    {
      id: 'toolbar.modeling.chamfer',
      title: 'Chamfer',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['c'],
      command: 'modeling:Chamfer',
    },
    {
      id: 'toolbar.modeling.offset-plane',
      title: 'Offset Plane',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['o'],
      command: 'modeling:Offset plane',
    },
    {
      id: 'toolbar.modeling.helix',
      title: 'Helix',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['h'],
      command: 'modeling:Helix',
    },
    {
      id: 'toolbar.modeling.insert',
      title: 'Insert',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['i'],
      command: 'code:Insert',
    },
    {
      id: 'toolbar.modeling.mirror3d',
      title: 'Mirror',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['m'],
      command: 'modeling:Mirror 3D',
    },
    {
      id: 'toolbar.sketch-no-face.cancel',
      title: 'Cancel Sketch',
      scopes: [MODE_SKETCH_NO_FACE_KEYMAP_SCOPE],
      keystrokes: ['escape'],
      command: TOOLBAR_COMMAND_IDS.sketching.exit,
    },
    ...createExitSketchBindings({
      id: 'toolbar.sketching.exit',
      scope: MODE_SKETCHING_KEYMAP_SCOPE,
      command: TOOLBAR_COMMAND_IDS.sketching.exit,
    }),
    {
      id: 'toolbar.sketching.cancel-tool',
      title: 'Cancel sketch tool',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['escape'],
      command: TOOLBAR_COMMAND_IDS.sketching.cancelTool,
    },
    {
      id: 'toolbar.sketching.line',
      title: 'Line',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['l'],
      command: TOOLBAR_COMMAND_IDS.sketching.line,
    },
    {
      id: 'toolbar.sketching.three-point-arc',
      title: 'Three-Point Arc',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['t'],
      command: TOOLBAR_COMMAND_IDS.sketching.threePointArc,
    },
    {
      id: 'toolbar.sketching.tangential-arc',
      title: 'Tangential Arc',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['a'],
      command: TOOLBAR_COMMAND_IDS.sketching.tangentialArc,
    },
    {
      id: 'toolbar.sketching.circle-center',
      title: 'Center Circle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['c'],
      command: TOOLBAR_COMMAND_IDS.sketching.circleCenter,
    },
    {
      id: 'toolbar.sketching.circle-three-points',
      title: '3-Point Circle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['alt+c'],
      command: TOOLBAR_COMMAND_IDS.sketching.circleThreePoints,
    },
    {
      id: 'toolbar.sketching.corner-rectangle',
      title: 'Corner Rectangle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['r'],
      command: TOOLBAR_COMMAND_IDS.sketching.cornerRectangle,
    },
    {
      id: 'toolbar.sketching.center-rectangle',
      title: 'Center Rectangle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['alt+r'],
      command: TOOLBAR_COMMAND_IDS.sketching.centerRectangle,
    },
    ...createExitSketchBindings({
      id: 'toolbar.sketch-solve.exit',
      scope: MODE_SKETCH_SOLVE_KEYMAP_SCOPE,
      command: TOOLBAR_COMMAND_IDS.sketchSolve.exit,
    }),
    {
      id: 'toolbar.sketch-solve.cancel',
      title: 'Cancel sketch solve action',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['escape'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.cancel,
    },
    {
      id: 'toolbar.sketch-solve.line',
      title: 'Line',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['l'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.line,
    },
    {
      id: 'toolbar.sketch-solve.point',
      title: 'Point',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['.'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.point,
    },
    {
      id: 'toolbar.sketch-solve.spline',
      title: 'Spline',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['s'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.spline,
    },
    {
      id: 'toolbar.sketch-solve.circle-center',
      title: 'Center Circle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['c'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.circleCenter,
    },
    {
      id: 'toolbar.sketch-solve.center-arc',
      title: 'Center Arc',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['a'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.centerArc,
    },
    {
      id: 'toolbar.sketch-solve.three-point-arc',
      title: '3-Point Arc',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['alt+a'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.threePointArc,
    },
    {
      id: 'toolbar.sketch-solve.tangential-arc',
      title: 'Tangential Arc',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+a'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.tangentialArc,
    },
    {
      id: 'toolbar.sketch-solve.trim',
      title: 'Trim',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['m'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.trim,
    },
    {
      id: 'toolbar.sketch-solve.corner-rectangle',
      title: 'Corner Rectangle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['r'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.cornerRectangle,
    },
    {
      id: 'toolbar.sketch-solve.center-rectangle',
      title: 'Center Rectangle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+r'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.centerRectangle,
    },
    {
      id: 'toolbar.sketch-solve.angled-rectangle',
      title: 'Angled Rectangle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['alt+r'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.angledRectangle,
    },
    {
      id: 'toolbar.sketch-solve.coincident',
      title: 'Coincident',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['x'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.coincident,
    },
    {
      id: 'toolbar.sketch-solve.midpoint',
      title: 'Midpoint',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+x'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.midpoint,
    },
    {
      id: 'toolbar.sketch-solve.tangent',
      title: 'Tangent',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['t'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.tangent,
    },
    {
      id: 'toolbar.sketch-solve.parallel',
      title: 'Parallel',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['b'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.parallel,
    },
    {
      id: 'toolbar.sketch-solve.perpendicular',
      title: 'Perpendicular',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+b'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.perpendicular,
    },
    {
      id: 'toolbar.sketch-solve.equal',
      title: 'Equal',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['e'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.equal,
    },
    {
      id: 'toolbar.sketch-solve.symmetric',
      title: 'Symmetric',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+e'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.symmetric,
    },
    {
      id: 'toolbar.sketch-solve.vertical',
      title: 'Vertical',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['v'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.vertical,
    },
    {
      id: 'toolbar.sketch-solve.horizontal',
      title: 'Horizontal',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['h'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.horizontal,
    },
    {
      id: 'toolbar.sketch-solve.fixed',
      title: 'Fixed',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['f'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.fixed,
    },
    {
      id: 'toolbar.sketch-solve.dimension',
      title: 'Dimension',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['d'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.dimension,
    },
    {
      id: 'toolbar.sketch-solve.horizontal-distance',
      title: 'Horizontal Distance',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['alt+d'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.horizontalDistance,
    },
    {
      id: 'toolbar.sketch-solve.vertical-distance',
      title: 'Vertical Distance',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+d'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.verticalDistance,
    },
    {
      id: 'toolbar.sketch-solve.construction',
      title: 'Construction',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['q'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.construction,
    },
  ],
}

export const defaultKeymapItem = defineRegistryItem({
  id: 'default-keymap',
  provides: [
    provide(keymapValueSpec, defaultKeymap, { key: defaultKeymap.source }),
  ],
})
