import { defineRegistryItem, provide } from '@kittycad/registry'
import { isDesktop } from '@src/lib/isDesktop'
import { getDeleteKeys } from '@src/lib/utils'
import {
  CODE_EDITOR_FOCUSED_KEYMAP_SCOPE,
  CODE_EDITOR_NOT_FOCUSED_KEYMAP_SCOPE,
  HOME_KEYMAP_SCOPE,
  type KeymapDocument,
  MODE_MODELING_KEYMAP_SCOPE,
  MODE_SKETCHING_KEYMAP_SCOPE,
  MODE_SKETCH_NO_FACE_KEYMAP_SCOPE,
  MODE_SKETCH_SOLVE_KEYMAP_SCOPE,
  PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE,
  keymapValueSpec,
} from '@src/registry/contracts/keymap'
import { APP_COMMAND_IDS } from '@src/registry/extensions/commands/appCommands'
import { TOOLBAR_COMMAND_IDS } from '@src/registry/extensions/commands/toolbarCommandIds'

const BASE_KEYMAP_SOURCE = 'Base'
const FILE_KEYMAP_SCOPES = [
  MODE_MODELING_KEYMAP_SCOPE,
  MODE_SKETCHING_KEYMAP_SCOPE,
  MODE_SKETCH_NO_FACE_KEYMAP_SCOPE,
  MODE_SKETCH_SOLVE_KEYMAP_SCOPE,
]

export const PROJECT_EXPLORER_COMMAND_IDS = {
  arrowLeft: 'project-explorer.arrow-left',
  arrowRight: 'project-explorer.arrow-right',
  arrowUp: 'project-explorer.arrow-up',
  arrowDown: 'project-explorer.arrow-down',
  enter: 'project-explorer.enter',
  rename: 'project-explorer.rename',
  delete: 'project-explorer.delete',
  copy: 'project-explorer.copy',
  paste: 'project-explorer.paste',
} as const

function createExitSketchBindings({
  id,
  scope,
  command,
  hidden,
  userBindingCommand,
}: {
  id: string
  scope: string
  command: string
  hidden?: boolean
  userBindingCommand?: string
}): KeymapDocument['bindings'] {
  return [
    {
      id,
      title: 'Exit Sketch',
      scopes: [scope],
      keystrokes: ['shift+escape'],
      command,
      hidden,
      userBindingCommand,
    },
  ]
}

export const defaultKeymap: KeymapDocument = {
  source: BASE_KEYMAP_SOURCE,
  bindings: [
    {
      id: 'command-palette.open',
      title: 'Open command palette',
      keystrokes: ['mod+k'],
      command: 'zds.commandPalette.open',
    },
    {
      id: 'command-palette.close',
      title: 'Close command palette',
      scopes: ['cmd-palette-open'],
      keystrokes: ['mod+k'],
      command: 'zds.commandPalette.close',
    },
    {
      id: 'command-palette.close-slash',
      title: 'Close command palette',
      scopes: ['cmd-palette-open'],
      keystrokes: ['mod+/'],
      command: 'zds.commandPalette.close',
      hidden: true,
      userBindingCommand: 'zds.commandPalette.close',
    },
    {
      id: 'settings.open',
      title: 'Open settings',
      keystrokes: [isDesktop() ? 'mod+,' : 'mod+shift+,'],
      command: 'zds.settings.open',
    },
    {
      id: 'settings.project',
      title: 'Project settings',
      scopes: ['settings-open'],
      keystrokes: ['p'],
      command: 'zds.settings.tab',
      arguments: {
        tab: 'project',
      },
    },
    {
      id: 'settings.user',
      title: 'User settings',
      scopes: ['settings-open'],
      keystrokes: ['u'],
      command: 'zds.settings.tab',
      arguments: {
        tab: 'user',
      },
    },
    {
      id: 'settings.focus-search',
      title: 'Focus settings search',
      scopes: ['settings-open'],
      keystrokes: ['ctrl+.'],
      command: APP_COMMAND_IDS.search.focusSettings,
    },
    {
      id: 'home.focus-project-search',
      title: 'Focus project search',
      scopes: [HOME_KEYMAP_SCOPE],
      keystrokes: ['ctrl+.'],
      command: APP_COMMAND_IDS.search.focusProjects,
    },
    {
      id: 'home.find-projects',
      title: 'Find projects',
      scopes: [HOME_KEYMAP_SCOPE],
      keystrokes: ['mod+f'],
      command: APP_COMMAND_IDS.search.focusProjects,
      hidden: true,
      userBindingCommand: APP_COMMAND_IDS.search.focusProjects,
    },
    {
      id: 'editor.undo',
      title: 'Undo',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: ['mod+z'],
      command: APP_COMMAND_IDS.editor.undo,
    },
    {
      id: 'editor.undo.code-editor-focused',
      title: 'Undo',
      scopes: [CODE_EDITOR_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['mod+z'],
      command: APP_COMMAND_IDS.editor.undo,
      hidden: true,
      userBindingCommand: APP_COMMAND_IDS.editor.undo,
    },
    {
      id: 'editor.redo',
      title: 'Redo',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: ['mod+shift+z'],
      command: APP_COMMAND_IDS.editor.redo,
    },
    {
      id: 'editor.redo.code-editor-focused',
      title: 'Redo',
      scopes: [CODE_EDITOR_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['mod+shift+z'],
      command: APP_COMMAND_IDS.editor.redo,
      hidden: true,
      userBindingCommand: APP_COMMAND_IDS.editor.redo,
    },
    ...(!isDesktop()
      ? [
          {
            id: 'editor.format',
            title: 'Format code',
            scopes: [CODE_EDITOR_NOT_FOCUSED_KEYMAP_SCOPE],
            keystrokes: ['alt+shift+f'],
            command: APP_COMMAND_IDS.editor.format,
          },
        ]
      : []),
    {
      id: 'editor.convert-to-variable',
      title: 'Convert to variable',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: ['ctrl+shift+c'],
      command: APP_COMMAND_IDS.editor.convertToVariable,
    },
    ...getDeleteKeys().map((deleteKey) => ({
      id: `modeling.delete-selection.${deleteKey}`,
      title: 'Delete selection',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: [deleteKey],
      command: APP_COMMAND_IDS.modeling.deleteSelection,
    })),
    {
      id: 'modeling.center-camera-on-selection',
      title: 'Center camera on selection',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: ['mod+alt+c'],
      command: APP_COMMAND_IDS.modeling.centerCameraOnSelection,
    },
    {
      id: 'modeling.select-all-in-current-sketch',
      title: 'Select all in current sketch',
      scopes: [
        MODE_SKETCHING_KEYMAP_SCOPE,
        MODE_SKETCH_NO_FACE_KEYMAP_SCOPE,
        MODE_SKETCH_SOLVE_KEYMAP_SCOPE,
      ],
      keystrokes: ['mod+a'],
      command: APP_COMMAND_IDS.modeling.selectAllInCurrentSketch,
    },
    {
      id: 'modeling.toggle-snap-to-grid',
      title: 'Toggle snap to grid',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: ['mod+g'],
      command: APP_COMMAND_IDS.modeling.toggleSnapToGrid,
    },
    {
      id: 'project-explorer.arrow-left',
      title: 'Close selected project explorer row',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['arrowleft'],
      command: PROJECT_EXPLORER_COMMAND_IDS.arrowLeft,
    },
    {
      id: 'project-explorer.arrow-right',
      title: 'Open selected project explorer row',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['arrowright'],
      command: PROJECT_EXPLORER_COMMAND_IDS.arrowRight,
    },
    {
      id: 'project-explorer.arrow-up',
      title: 'Move project explorer selection up',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['arrowup'],
      command: PROJECT_EXPLORER_COMMAND_IDS.arrowUp,
    },
    {
      id: 'project-explorer.arrow-down',
      title: 'Move project explorer selection down',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['arrowdown'],
      command: PROJECT_EXPLORER_COMMAND_IDS.arrowDown,
    },
    {
      id: 'project-explorer.enter',
      title: 'Open selected project explorer file',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['enter'],
      command: PROJECT_EXPLORER_COMMAND_IDS.enter,
    },
    {
      id: 'project-explorer.rename',
      title: 'Rename selected project explorer row',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['f2'],
      command: PROJECT_EXPLORER_COMMAND_IDS.rename,
    },
    {
      id: 'project-explorer.delete',
      title: 'Delete selected project explorer row',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['mod+backspace'],
      command: PROJECT_EXPLORER_COMMAND_IDS.delete,
    },
    {
      id: 'project-explorer.copy',
      title: 'Copy selected project explorer row',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['mod+c'],
      command: PROJECT_EXPLORER_COMMAND_IDS.copy,
    },
    {
      id: 'project-explorer.paste',
      title: 'Paste into selected project explorer row',
      scopes: [PROJECT_EXPLORER_FOCUSED_KEYMAP_SCOPE],
      keystrokes: ['mod+v'],
      command: PROJECT_EXPLORER_COMMAND_IDS.paste,
    },
    {
      id: 'view.top',
      title: 'Top view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '1'],
      command: 'standardViews:Top view',
    },
    {
      id: 'view.right',
      title: 'Right view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '2'],
      command: 'standardViews:Right view',
    },
    {
      id: 'view.front',
      title: 'Front view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '3'],
      command: 'standardViews:Front view',
    },
    {
      id: 'view.back',
      title: 'Back view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '4'],
      command: 'standardViews:Back view',
    },
    {
      id: 'view.bottom',
      title: 'Bottom view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '5'],
      command: 'standardViews:Bottom view',
    },
    {
      id: 'view.left',
      title: 'Left view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', '6'],
      command: 'standardViews:Left view',
    },
    {
      id: 'view.zoom-to-fit',
      title: 'Zoom to fit',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', 'f'],
      command: 'standardViews:Zoom to fit',
    },
    {
      id: 'view.reset',
      title: 'Reset view',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['v', 'r'],
      command: APP_COMMAND_IDS.view.reset,
    },
    {
      id: 'view.reset-with-modifier',
      title: 'Reset view',
      scopes: FILE_KEYMAP_SCOPES,
      keystrokes: ['mod+alt+x'],
      command: APP_COMMAND_IDS.view.reset,
    },
    {
      id: 'toolbar.modeling.sketch',
      title: 'Start or edit sketch',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['s'],
      command: TOOLBAR_COMMAND_IDS.modeling.sketch,
    },
    {
      id: 'toolbar.modeling.extrude',
      title: 'Extrude',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['e'],
      command: 'modeling:Extrude',
    },
    {
      id: 'toolbar.modeling.sweep',
      title: 'Sweep',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['w'],
      command: 'modeling:Sweep',
    },
    {
      id: 'toolbar.modeling.loft',
      title: 'Loft',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['l'],
      command: 'modeling:Loft',
    },
    {
      id: 'toolbar.modeling.revolve',
      title: 'Revolve',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['r'],
      command: 'modeling:Revolve',
    },
    {
      id: 'toolbar.modeling.fillet',
      title: 'Fillet',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['f'],
      command: 'modeling:Fillet',
    },
    {
      id: 'toolbar.modeling.chamfer',
      title: 'Chamfer',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['c'],
      command: 'modeling:Chamfer',
    },
    {
      id: 'toolbar.modeling.offset-plane',
      title: 'Offset Plane',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['o'],
      command: 'modeling:Offset plane',
    },
    {
      id: 'toolbar.modeling.helix',
      title: 'Helix',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['h'],
      command: 'modeling:Helix',
    },
    {
      id: 'toolbar.modeling.insert',
      title: 'Insert',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['i'],
      command: 'code:Insert',
    },
    {
      id: 'toolbar.modeling.mirror3d',
      title: 'Mirror',
      scopes: [MODE_MODELING_KEYMAP_SCOPE],
      keystrokes: ['m'],
      command: 'modeling:Mirror 3D',
    },
    {
      id: 'toolbar.sketch-no-face.cancel',
      title: 'Cancel Sketch',
      scopes: [MODE_SKETCH_NO_FACE_KEYMAP_SCOPE],
      keystrokes: ['escape'],
      command: TOOLBAR_COMMAND_IDS.sketching.exit,
    },
    ...createExitSketchBindings({
      id: 'toolbar.sketch-legacy.exit',
      scope: MODE_SKETCHING_KEYMAP_SCOPE,
      command: TOOLBAR_COMMAND_IDS.sketching.exit,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.exit,
    }),
    {
      id: 'toolbar.sketch-legacy.cancel-tool',
      title: 'Cancel sketch tool',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['escape'],
      command: TOOLBAR_COMMAND_IDS.sketching.cancelTool,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.cancel,
    },
    {
      id: 'toolbar.sketch-legacy.line',
      title: 'Line',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['l'],
      command: TOOLBAR_COMMAND_IDS.sketching.line,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.line,
    },
    {
      id: 'toolbar.sketch-legacy.three-point-arc',
      title: 'Three-Point Arc',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['t'],
      command: TOOLBAR_COMMAND_IDS.sketching.threePointArc,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.threePointArc,
    },
    {
      id: 'toolbar.sketch-legacy.tangential-arc',
      title: 'Tangential Arc',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['a'],
      command: TOOLBAR_COMMAND_IDS.sketching.tangentialArc,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.tangentialArc,
    },
    {
      id: 'toolbar.sketch-legacy.circle-center',
      title: 'Center Circle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['c'],
      command: TOOLBAR_COMMAND_IDS.sketching.circleCenter,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.circleCenter,
    },
    {
      id: 'toolbar.sketch-legacy.circle-three-points',
      title: '3-Point Circle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['alt+c'],
      command: TOOLBAR_COMMAND_IDS.sketching.circleThreePoints,
      hidden: true,
    },
    {
      id: 'toolbar.sketch-legacy.corner-rectangle',
      title: 'Corner Rectangle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['r'],
      command: TOOLBAR_COMMAND_IDS.sketching.cornerRectangle,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.cornerRectangle,
    },
    {
      id: 'toolbar.sketch-legacy.center-rectangle',
      title: 'Center Rectangle',
      scopes: [MODE_SKETCHING_KEYMAP_SCOPE],
      keystrokes: ['alt+r'],
      command: TOOLBAR_COMMAND_IDS.sketching.centerRectangle,
      hidden: true,
      userBindingCommand: TOOLBAR_COMMAND_IDS.sketchSolve.centerRectangle,
    },
    ...createExitSketchBindings({
      id: 'toolbar.sketch.exit',
      scope: MODE_SKETCH_SOLVE_KEYMAP_SCOPE,
      command: TOOLBAR_COMMAND_IDS.sketchSolve.exit,
    }),
    {
      id: 'toolbar.sketch.cancel',
      title: 'Cancel sketch action',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['escape'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.cancel,
    },
    {
      id: 'toolbar.sketch.line',
      title: 'Line',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['l'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.line,
    },
    {
      id: 'toolbar.sketch.point',
      title: 'Point',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['.'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.point,
    },
    {
      id: 'toolbar.sketch.spline',
      title: 'Spline',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['s'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.spline,
    },
    {
      id: 'toolbar.sketch.circle-center',
      title: 'Center Circle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['c'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.circleCenter,
    },
    {
      id: 'toolbar.sketch.center-arc',
      title: 'Center Arc',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['a'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.centerArc,
    },
    {
      id: 'toolbar.sketch.three-point-arc',
      title: '3-Point Arc',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['alt+a'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.threePointArc,
    },
    {
      id: 'toolbar.sketch.tangential-arc',
      title: 'Tangential Arc',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+a'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.tangentialArc,
    },
    {
      id: 'toolbar.sketch.trim',
      title: 'Trim',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['m'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.trim,
    },
    {
      id: 'toolbar.sketch.corner-rectangle',
      title: 'Corner Rectangle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['r'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.cornerRectangle,
    },
    {
      id: 'toolbar.sketch.center-rectangle',
      title: 'Center Rectangle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+r'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.centerRectangle,
    },
    {
      id: 'toolbar.sketch.angled-rectangle',
      title: 'Angled Rectangle',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['alt+r'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.angledRectangle,
    },
    {
      id: 'toolbar.sketch.coincident',
      title: 'Coincident',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['x'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.coincident,
    },
    {
      id: 'toolbar.sketch.midpoint',
      title: 'Midpoint',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+x'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.midpoint,
    },
    {
      id: 'toolbar.sketch.tangent',
      title: 'Tangent',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['t'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.tangent,
    },
    {
      id: 'toolbar.sketch.parallel',
      title: 'Parallel',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['b'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.parallel,
    },
    {
      id: 'toolbar.sketch.perpendicular',
      title: 'Perpendicular',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+b'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.perpendicular,
    },
    {
      id: 'toolbar.sketch.equal',
      title: 'Equal',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['e'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.equal,
    },
    {
      id: 'toolbar.sketch.symmetric',
      title: 'Symmetric',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+e'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.symmetric,
    },
    {
      id: 'toolbar.sketch.vertical',
      title: 'Vertical',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['v'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.vertical,
    },
    {
      id: 'toolbar.sketch.horizontal',
      title: 'Horizontal',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['h'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.horizontal,
    },
    {
      id: 'toolbar.sketch.fixed',
      title: 'Fixed',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['f'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.fixed,
    },
    {
      id: 'toolbar.sketch.dimension',
      title: 'Dimension',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['d'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.dimension,
    },
    {
      id: 'toolbar.sketch.horizontal-distance',
      title: 'Horizontal Distance',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['alt+d'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.horizontalDistance,
    },
    {
      id: 'toolbar.sketch.vertical-distance',
      title: 'Vertical Distance',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['shift+d'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.verticalDistance,
    },
    {
      id: 'toolbar.sketch.construction',
      title: 'Construction',
      scopes: [MODE_SKETCH_SOLVE_KEYMAP_SCOPE],
      keystrokes: ['q'],
      command: TOOLBAR_COMMAND_IDS.sketchSolve.construction,
    },
  ],
}

export const defaultKeymapItem = defineRegistryItem({
  id: 'default-keymap',
  provides: [
    provide(keymapValueSpec, defaultKeymap, { key: defaultKeymap.source }),
  ],
})
