// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Coincident } from "./Coincident";
import type { Parallel } from "./Parallel";

export type ApiConstraint = { "Coincident": Coincident } | { "Parallel": Parallel };
