// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Number } from "./Number";

export type Expr = { "Number": Number } | { "Var": Number } | { "Variable": string };
