// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiPoint2d } from "./ApiPoint2d";
import type { Expr } from "./Expr";

export type LineCtor = { start: ApiPoint2d<Expr>, end: ApiPoint2d<Expr>, };
