// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiPoint2d } from "./ApiPoint2d";
import type { ApiStartOrEnd } from "./ApiStartOrEnd";
import type { Expr } from "./Expr";

export type MidPointLineCtor = { midpoint: ApiPoint2d<Expr>, start_or_end: ApiStartOrEnd<ApiPoint2d<Expr>>, };
