// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumericSuffix = "None" | "Count" | "Length" | "Angle" | "Mm" | "Cm" | "M" | "Inch" | "Ft" | "Yd" | "Deg" | "Rad" | "Unknown";
