// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiFileId } from "./ApiFileId";
import type { ApiObjectId } from "./ApiObjectId";
import type { ApiProjectId } from "./ApiProjectId";
import type { ApiSettings } from "./ApiSettings";
import type { ApiVersion } from "./ApiVersion";
import type { Object } from "./Object";

export type SceneGraph = { project: ApiProjectId, file: ApiFileId, version: ApiVersion, objects: Array<Object>, settings: ApiSettings, sketch_mode: ApiObjectId | null, };
