---
source: kcl-lib/src/simulation_tests.rs
description: Lints scrub-daddy-holder.kcl
---
[
  {
    "finding": {
      "code": "Z0004",
      "title": "profiles should not be chained",
      "description": "Functions like startProfile, circle, ellipse, rectangle, polygon and others that start a new profile should not be chained together in a pipeline ✏️\n\nWhen using multiple profile functions in a pipeline, only the last profile is returned. This can lead to unexpected results if earlier profiles are intended to contribute to the final shape.\n\nInstead, try assigning the result of each profile to a variable and when extruding, use an array of those variables.\n",
      "experimental": false
    },
    "description": "Profiles should not be chained together in a pipeline.",
    "pos": [
      694,
      769,
      0
    ],
    "overridden": false,
    "suggestion": {
      "title": "Use separate profile variables and handle them all using an array.",
      "insert": "// Scrub Daddy Sponge Holder\n// A scrub daddy is a sponge with a course texture which has the shape of a smiling face. This holder attaches magnetically to the wall of your sink or other locations where a sponge may be needed. The holder is designed to fit through the eye openings on the sponge. This is designed to fit mangets with a diameter of 6mm and thickness of 3 mm.\n\n\n\n\n@settings(defaultLengthUnit = mm)\n\nmagnetDiameter = 6.2\nmagnetThickness = 3\nspongeThickness = 40\nspongeEyeDiameter = 14\nspongeEyeCenter2Center = 34\nspongeDiameter = 100\n\nsketch = startSketchOn(XY)\n\n// create the magnets so we can subtract them from the holder later\nmagnets = startProfile(sketch, at = [0, 0])\nprofile1 = circle(sketch, center = [spongeEyeCenter2Center / 2, 0], diameter = magnetDiameter)\n  |> patternCircular2d(instances = 2, center = [0, 0])\n  |> extrude(length = magnetThickness)\nbase = startProfile(\n       sketch,\n       at = [\n         -spongeDiameter / 2 * 0.6,\n         -spongeEyeDiameter / 2 * 1.5\n       ],\n     )\n  |> xLine(length = spongeDiameter * 0.6, tag = $line001)\n  |> yLine(length = spongeEyeDiameter * 1.5, tag = $line002)\n  |> xLine(endAbsolute = profileStartX(), tag = $line003)\n  |> close(tag = $line004)\n  |> extrude(length = magnetThickness * 1.5)\n  |> subtract(tools = [magnets])\n  |> fillet(\n       radius = 5,\n       tags = [\n         getNextAdjacentEdge(line001),\n         getNextAdjacentEdge(line002),\n         getNextAdjacentEdge(line003),\n         getNextAdjacentEdge(line004)\n       ],\n     )\n\n// create the holder pegs which go into the eyes of the sponge\nholder = startSketchOn(base, face = END)\n  |> circle(center = [spongeEyeCenter2Center / 2, 0], diameter = spongeEyeDiameter, tag = $circ001)\n  |> extrude(length = spongeThickness - magnetThickness)\n  |> fillet(radius = 2, tags = [getOppositeEdge(circ001), circ001])\n  |> patternCircular3d(instances = 2, center = [0, 0, 0], axis = Z)\n",
      "source_range": [
        0,
        1939,
        0
      ]
    }
  }
]
