// Field monitor stand
// Stand for a Feelworld FW760 7 inch Field Monitor


plate_length = 121
plate_length_base = 60

width = 3

plate_width = 62 + 4
hole_radius = 4 / 2 // 2.84
hole_distance_y = 52.1 + 2 * hole_radius
hole_distance_x = 75.2 + 2 * hole_radius

plate_hole_distance_y_1 = plate_width / 2 + hole_distance_y / 2
plate_hole_distance_y_2 = plate_width / 2 - (hole_distance_y / 2)
plate_hole_distance_x_1 = plate_length - 21 - 0
plate_hole_distance_x_2 = plate_length - 21 - hole_distance_x

angle = 110deg

// Plates
sketch001 = startSketchOn(YZ)
profile001 = startProfile(sketch001, at = [-plate_length_base, 0])
  |> xLine(length = plate_length_base)
  |> angledLine(angle = angle, length = plate_length, tag = $seg01)
  |> angledLine(angle = angle + 90deg, length = width, tag = $seg02)
  |> angledLine(angle = angle + 90deg + 90deg, endAbsoluteY = width, tag = $seg03)
  |> angledLine(angle = 180deg, endAbsoluteX = -plate_length_base, tag = $seg04)
  |> line(endAbsolute = [-plate_length_base, 0], tag = $seg05)
profile002 = startProfile(sketch001, at = [0, 0])
  |> xLine(length = -15)
  |> line(end = [0, 35])
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
extrude001 = extrude(
  profile001,
  length = plate_width,
  tagStart = $capStart001,
  tagEnd = $capEnd001,
)

extrude002 = extrude(profile002, length = 2)

// Holes
sketch003 = startSketchOn(extrude001, face = seg01)
hole1 = circle(
  sketch003,
  center = [
    plate_hole_distance_x_1,
    plate_hole_distance_y_1
  ],
  radius = hole_radius,
)
hole2 = circle(
  sketch003,
  center = [
    plate_hole_distance_x_1,
    plate_hole_distance_y_2
  ],
  radius = hole_radius,
)
hole3 = circle(
  sketch003,
  center = [
    plate_hole_distance_x_2,
    plate_hole_distance_y_1
  ],
  radius = hole_radius,
)
hole4 = circle(
  sketch003,
  center = [
    plate_hole_distance_x_2,
    plate_hole_distance_y_2
  ],
  radius = hole_radius,
)

hole1_e = extrude(hole1, length = -10, method = NEW)
hole2_e = extrude(hole2, length = -10, method = NEW)
hole3_e = extrude(hole3, length = -10, method = NEW)

hole4_e = extrude(hole4, length = -10, method = NEW)

subtract = subtract(extrude001, tools = [hole1_e, hole2_e, hole3_e, hole4_e])
fillet(subtract, tags = getCommonEdge(faces = [seg02, capStart001]), radius = 5)
fillet(subtract, tags = getCommonEdge(faces = [seg02, capEnd001]), radius = 5)
fillet(subtract, tags = getCommonEdge(faces = [seg05, capStart001]), radius = 5)
fillet(subtract, tags = getCommonEdge(faces = [seg05, capEnd001]), radius = 5)

