// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifier of a source file.  Uses a u32 to keep the size small.
 */
export type ModuleId = number;
