// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "kcl_csharp";





        /// <summary>
        ///  Start a KCL session backed by a live engine connection.
        ///  Pass `auth_token` as null or an empty string to fall back to the environment.
        ///  The returned `session` handle remains valid until exactly one call to `free_session`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "start_session", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern SessionStartResult start_session(byte* auth_token);

        /// <summary>
        ///  Run the KCL program in an existing session and export the current scene.
        ///  Pass `current_file` as null or an empty string when there is no on-disk file path.
        ///
        ///  Caller requirements:
        ///  - `session` must be a non-null handle returned by `start_session`.
        ///  - `session` must remain valid for the entire call.
        ///  - Do not call `free_session(session)` until this function has returned.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "session_run_contents_and_export", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ExportResult session_run_contents_and_export(SessionHandle* session, byte* contents, byte* current_file, FileExportFormat export_format);

        /// <summary>
        ///  Run the KCL file in an existing session and export the current scene.
        ///  Input: a filepath to a .kcl file, or a directory containing a `main.kcl`.
        ///
        ///  Caller requirements:
        ///  - `session` must be a non-null handle returned by `start_session`.
        ///  - `session` must remain valid for the entire call.
        ///  - Do not call `free_session(session)` until this function has returned.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "session_run_file_and_export", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ExportResult session_run_file_and_export(SessionHandle* session, byte* kcl_source_file, FileExportFormat export_format);

        /// <summary>
        ///  Run the KCL file, and export it to some file format.
        ///  Input: a filepath to a .kcl file, or a directory containing a `main.kcl`.
        ///  Pass `auth_token` as null or an empty string to fall back to the environment.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "run_file_and_export", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ExportResult run_file_and_export(byte* kcl_source_file, FileExportFormat export_format, byte* auth_token);

        /// <summary>
        ///  Run the KCL program, and export it to some file format.
        ///  Input: a KCL program in a string.
        ///  Pass `auth_token` as null or an empty string to fall back to the environment.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "run_contents_and_export", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ExportResult run_contents_and_export(byte* contents, FileExportFormat export_format, byte* auth_token);

        /// <summary>
        ///  Users must call this exactly once for each successful `start_session` result
        ///  after reading the error message, if any.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "free_session_start_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_session_start_result(SessionStartResult result);

        /// <summary>
        ///  Users must call this exactly once for each successful `run_*_and_export` result,
        ///  after they have copied out the data.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "free_export_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_export_result(ExportResult result);

        /// <summary>
        ///  Close the live engine connection for this session and free the session handle.
        ///
        ///  Caller requirements:
        ///  - Call this exactly once for each successful `start_session` result.
        ///  - Do not call this concurrently with `session_run_contents_and_export` or
        ///    `session_run_file_and_export` on the same handle.
        ///  - After this returns, `session` is invalid and must never be used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "free_session", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_session(SessionHandle* session);


    }

    /// <summary>
    ///  Opaque handle to a live KCL session.
    ///
    ///  Caller requirements:
    ///  - Treat this as an opaque pointer returned by `start_session`.
    ///  - Keep it alive until exactly one call to `free_session`.
    ///  - Do not call `free_session` concurrently with any other use of the same handle.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SessionHandle
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ExportedFile
    {
        /// <summary>
        ///  NUL-terminated UTF-8 string owned by Rust.
        /// </summary>
        public byte* name;
        /// <summary>
        ///  File bytes owned by Rust.
        /// </summary>
        public byte* contents;
        public nuint contents_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ErrorInfo
    {
        public KclErrorKind kind;
        public byte* msg;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ExportResult
    {
        /// <summary>
        ///  If true, then `error` is set, it should be read and handled.
        ///  `exports` is invalid and should not be read.
        /// </summary>
        [MarshalAs(UnmanagedType.U1)] public bool error_set;
        public ErrorInfo* error;
        /// <summary>
        ///  Should only be read if `error_set` is false.
        /// </summary>
        public ExportedFile* exports;
        public nuint exports_len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct SessionStartResult
    {
        public SessionHandle* session;
        [MarshalAs(UnmanagedType.U1)] public bool setup_error_set;
        public byte* setup_error;
    }


    internal enum KclErrorKind : uint
    {
        Lexical,
        Syntax,
        Semantic,
        ImportCycle,
        Argument,
        Type,
        Io,
        Unexpected,
        ValueAlreadyDefined,
        UndefinedValue,
        InvalidExpression,
        MaxCallStack,
        Engine,
        EngineHangup,
        EngineInternal,
        Internal,
        Setup,
    }

    internal enum FileExportFormat : uint
    {
        /// <summary>
        ///  Autodesk Filmbox (FBX) format. &lt;https://en.wikipedia.org/wiki/FBX&gt;
        /// </summary>
        Fbx,
        /// <summary>
        ///  Binary glTF 2.0.
        ///
        ///  This is a single binary with .glb extension.
        ///
        ///  This is better if you want a compressed format as opposed to the human readable
        ///  glTF that lacks compression.
        /// </summary>
        Glb,
        /// <summary>
        ///  glTF 2.0.
        ///  Embedded glTF 2.0 (pretty printed).
        ///
        ///  Single JSON file with .gltf extension binary data encoded as
        ///  base64 data URIs.
        ///
        ///  The JSON contents are pretty printed.
        ///
        ///  It is human readable, single file, and you can view the
        ///  diff easily in a git commit.
        /// </summary>
        Gltf,
        /// <summary>
        ///  The OBJ file format. &lt;https://en.wikipedia.org/wiki/Wavefront_.obj_file&gt;
        ///  It may or may not have an an attached material (mtl // mtllib) within the file,
        ///  but we interact with it as if it does not.
        /// </summary>
        Obj,
        /// <summary>
        ///  The PLY file format. &lt;https://en.wikipedia.org/wiki/PLY_(file_format)&gt;
        /// </summary>
        Ply,
        /// <summary>
        ///  The STEP file format. &lt;https://en.wikipedia.org/wiki/ISO_10303-21&gt;
        /// </summary>
        Step,
        /// <summary>
        ///  The STL file format. &lt;https://en.wikipedia.org/wiki/STL_(file_format)&gt;
        /// </summary>
        Stl,
    }


}
