on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/rust-toolchain.toml'
      - .github/workflows/cargo-bench.yml
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/rust-toolchain.toml'
      - .github/workflows/cargo-bench.yml
  workflow_dispatch:
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: cargo bench
jobs:
  cargo-bench:
    name: Benchmark with iai
    runs-on: ubuntu-latest-8-cores
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          cargo install cargo-criterion
          sudo apt update
          sudo apt install -y valgrind
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.6.1
      - name: Benchmark kcl library
        shell: bash
        run: |-
          cd src/wasm-lib/kcl; cargo bench --all-features -- iai
        env:
          KITTYCAD_API_TOKEN: ${{secrets.KITTYCAD_API_TOKEN}}

