on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/rust-toolchain.toml'
      - .github/workflows/cargo-build.yml
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/rust-toolchain.toml'
      - .github/workflows/cargo-build.yml
name: cargo build
jobs:
  cargobuild:
    name: cargo build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ['src/wasm-lib']
    steps:
      - uses: actions/checkout@v4

      - name: Install latest rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - name: install dependencies
        if: matrix.dir ==  'src-tauri'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.6.1

      - name: Run cargo build
        run: |
          cd "${{ matrix.dir }}"
          cargo build --all
        shell: bash
