on:
  push:
    branches:
      - main
  pull_request:
permissions:
  packages: read
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: cargo fmt
jobs:
  cargofmt:
    name: cargo fmt
    runs-on: namespace-profile-ubuntu-2-cores
    steps:
      - uses: actions/checkout@v7.0.1
      - id: filter
        name: Check for Rust changes
        uses: dorny/paths-filter@v4.0.3
        with:
          filters: |
            rust:
              - 'rust/**'
              - '.github/workflows/cargo-fmt.yml'
              - '.github/workflows/nightly-rust-toolchain.toml'
      - name: Use correct Rust toolchain
        if: steps.filter.outputs.rust == 'true'
        shell: bash
        run: |
          cp .github/workflows/nightly-rust-toolchain.toml rust-toolchain.toml
      - name: Install rust
        if: steps.filter.outputs.rust == 'true'
        uses: actions-rust-lang/setup-rust-toolchain@v1.17.0
        with:
          cache-workspaces: rust
          components: rustfmt
          rustflags: '' # Use .cargo/config.toml

      - name: Run nightly cargo fmt
        if: steps.filter.outputs.rust == 'true'
        run: |
          cd rust
          cargo +nightly fmt -- --check
        shell: bash
