name: Identify Duplicate Issues

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day

permissions:
  issues: write

jobs:
  find-duplicates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub openai

      - name: Run script to identify duplicates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python .github/scripts/find_duplicate_issues.py
