on:
  push:
    branches:
      - main
    paths:
      - 'public/kcl-samples/**'
  pull_request:
    paths:
      - .github/workflows/pr-kcl-samples-repo.yml
  workflow_dispatch:
name: Create PR in kcl-samples repo
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  pr-kcl-samples-repo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ secrets.GH_ORG_APP_ID }}
          private-key: ${{ secrets.GH_ORG_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v4
      # Checkout the other repo since we want to update the files there.
      - uses: actions/checkout@v4
        with:
          repository: 'KittyCAD/kcl-samples'
          ref: next
          path: kcl-samples-repo
          token: ${{ steps.app-token.outputs.token }}
      - name: Move files to repo work tree
        shell: bash
        run: |
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='screenshots' \
            --exclude='step' \
            public/kcl-samples/ kcl-samples-repo/
      - name: Commit the changes in the repo
        shell: bash
        run: |
          cd kcl-samples-repo
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          export NEW_BRANCH="update-from-modeling-app"
          git switch -c "$NEW_BRANCH"
          git add --all .
          git commit -m "Updates from modeling-app repo" || exit 0
          git push -f origin "$NEW_BRANCH"
          gh pr create --title "Update from modeling-app" \
              --body "Updating files from the modeling-app repo" \
              --head "$NEW_BRANCH" \
              --reviewer jtran \
              --base next || true
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}


