name: publish-kcl-wasm-lib

on:
  workflow_run:
    workflows:
      - build-apps
    types:
      - completed

permissions:
  id-token: write
  contents: write

jobs:
  publish-kcl-wasm-lib:
    name: publish-kcl-wasm-lib
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - uses: actions/download-artifact@v8
        with:
          name: prepared-files
          path: prepared-files
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use prepared wasm package
        run: |
          rm -rf rust/kcl-wasm-lib/pkg
          mkdir -p rust/kcl-wasm-lib
          cp -R prepared-files/rust/kcl-wasm-lib/pkg rust/kcl-wasm-lib/pkg

      - name: Skip tag creation for CI testing
        working-directory: rust/kcl-wasm-lib/pkg
        run: |
          echo "Skipping tag creation/push for CI testing."
          echo "Would have tagged: v$(cat package.json | jq -r .version)"

      - name: Publish package
        working-directory: rust/kcl-wasm-lib/pkg
        run: npm publish --access public --provenance --dry-run
