name: update-e2e-branch

# This is used to sync the `all-e2e` branch with the `main` branch for the
# logic in the test utility `orRunWhenFullSuiteEnabled()` that allows all e2e
# tests to run on a particular branch to analyze failures metrics in Axiom.

on:
  schedule:
    - cron: '0 * * * *' # runs every hour

permissions:
  contents: write

jobs:
  update-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.MODELING_APP_GH_APP_ID }}
          private-key: ${{ secrets.MODELING_APP_GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Sync with main
        run: |
          # checkout our branch
          git checkout all-e2e || git checkout -b all-e2e
          # fetch origin
          git fetch origin
          # reset to main
          git reset --hard origin/main
          # get a new SHA to prevent overwriting the commit status on main
          git commit --amend --message="[all-e2e] $(git log --max-count=1 --pretty=%B)"
          # force push it
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}.git
          git push --force origin all-e2e
